In [1]:
# ! pip install pypower --quiet

In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import torch
from torch import nn
from torch.utils.data import DataLoader, Dataset
import os

SEED = 2024
torch.manual_seed(SEED)

# The solution of the AC-OPF provides a setpoint for power generations in order to satisfy a specific state of electricity consumtion !!!!!!!

In [3]:
# Load the network for Case14
net = {
    "baseMVA": 100.0,
## area data
    "areas": np.array([[1, 4]]),
## bus data
###	bus_i	type	Pd	Qd	Gs	Bs	area	Vm	Va	baseKV	zone	Vmax	Vmin
    "bus": np.array([
                    [1,	 3,	 0.0,	 0.0,	 0.0,	 0.0,	 1,	    1.00000,  0.00000,	 1.0,	 1,	    1.06000,	0.94000],
                	[2,	 2,	 21.7,	 12.7,	 0.0,	 0.0,	 1,	    1.00000,  0.00000,	 1.0,	 1,	    1.06000,    0.94000],
                	[3,	 2,	 94.2,	 19.0,	 0.0,	 0.0,	 1,	    1.00000,  0.00000,	 1.0,	 1,	    1.06000,    0.94000],
                	[4,	 1,	 47.8,	 -3.9,	 0.0,	 0.0,	 1,	    1.00000,  0.00000,	 1.0,	 1,	    1.06000,	0.94000],
                	[5,  1,	 7.6,	 1.6,	 0.0,	 0.0,	 1,	    1.00000,  0.00000,	 1.0,	 1,	    1.06000,	0.94000],
                	[6,	 2,	 11.2,	 7.5,	 0.0,	 0.0,	 1,	    1.00000,  0.00000,	 1.0,	 1,	    1.06000,	0.94000],
                	[7,	 1,	 0.0,	 0.0,	 0.0,	 0.0,	 1,	    1.00000,  0.00000,	 1.0,	 1,	    1.06000,	0.94000],
                	[8,	 2,	 0.0,	 0.0,	 0.0,	 0.0,	 1,     1.00000,  0.00000,	 1.0,	 1,	    1.06000,	0.94000],
                	[9,	 1,	 29.5,	 16.6,	 0.0,	 19.0,	 1,	    1.00000,  0.00000,	 1.0,	 1,	    1.06000,    0.94000],
                	[10, 1,	 9.0,	 5.8,	 0.0,	 0.0,	 1,	    1.00000,  0.00000,	 1.0,	 1,	    1.06000,	0.94000],
                	[11, 1,	 3.5,	 1.8,	 0.0,	 0.0,	 1,	    1.00000,  0.00000,	 1.0,	 1,	    1.06000,	0.94000],
                	[12, 1,	 6.1,	 1.6,	 0.0,	 0.0,	 1,	    1.00000,  0.00000,	 1.0,	 1,	    1.06000,	0.94000],
                	[13, 1,	 13.5,	 5.8,	 0.0,	 0.0,	 1,	    1.00000,  0.00000,	 1.0,	 1,	    1.06000,	0.94000],
                	[14, 1,	 14.9,	 5.0,	 0.0,	 0.0,	 1,	    1.00000,  0.00000,	 1.0,	 1,	    1.06000,	0.94000],
                ]),
    
## generator data
###	bus	Pg	Qg	Qmax	Qmin	Vg	mBase	status	Pmax	Pmin
    "gen": np.array([
                	[1,	 170.0,	 5.0,	 10.0,	  0.0,	 1.0,	 100.0,	 1,	 340,  0.0],
                	[2,	 29.5,	 0.0,	 30.0,	 -30.0,	 1.0,	 100.0,	 1,	 59,   0.0],
                	[3,	 0.0,	 20.0,	 40.0,	  0.0,	 1.0,	 100.0,	 1,	 0,	   0.0],
                	[6,	 0.0,	 9.0,	 24.0,	 -6.0,	 1.0,	 100.0,	 1,	 0,	   0.0],
                	[8,	 0.0,	 9.0,	 24.0,	 -6.0,	 1.0,	 100.0,	 1,	 0,	   0.0]
                 ]),
    
## generator cost data
###	2	startup	shutdown	n	c(n-1)	...	c0
    "gencost": np.array([
                	[2,	 0.0,	 0.0,	 3,	   0.000000,	   7.920951,	   0.000000],
                	[2,	 0.0,	 0.0,	 3,	   0.000000,	  23.269494,	   0.000000],
                	[2,	 0.0,	 0.0,	 3,	   0.000000,	   0.000000,	   0.000000],
                	[2,	 0.0,	 0.0,	 3,	   0.000000,	   0.000000,	   0.000000],
                	[2,	 0.0,	 0.0,	 3,	   0.000000,	   0.000000,	   0.000000]
                ]),
    
## branch data
###	fbus	tbus	r	x	b	rateA	rateB	rateC	ratio	angle	status	angmin	angmax
    "branch": np.array([
                    [1,	 2,	 0.01938,	 0.05917,	 0.0528, 472,	 472,	 472,	 0.0,	 0.0,	 1,	 -30.0,	 30.0],
                	[1,	 5,	 0.05403,	 0.22304,	 0.0492, 128,	 128,	 128,	 0.0,	 0.0,	 1,	 -30.0,	 30.0],
                	[2,	 3,	 0.04699,	 0.19797,	 0.0438, 145,	 145,	 145,	 0.0,	 0.0,	 1,	 -30.0,	 30.0],
                    [2,	 4,	 0.05811,	 0.17632,	 0.034,	 158,	 158,	 158,	 0.0,	 0.0,	 1,	 -30.0,	 30.0],
                	[2,	 5,	 0.05695,	 0.17388,	 0.0346, 161,	 161,	 161,	 0.0,	 0.0,	 1,	 -30.0,	 30.0],
                	[3,	 4,	 0.06701,	 0.17103,	 0.0128, 160,	 160,	 160,	 0.0,	 0.0,	 1,	 -30.0,	 30.0],
                	[4,	 5,	 0.01335,	 0.04211,	 0.0,	 664,	 664,	 664,	 0.0,	 0.0,	 1,	 -30.0,	 30.0],
                	[4,	 7,	 0.0,	     0.20912,	 0.0,	 141,	 141,	 141,	 0.978,	 0.0,	 1,	 -30.0,	 30.0],
                	[4,	 9,	 0.0,	     0.55618,	 0.0,	 53,	 53,	 53,	 0.969,	 0.0,	 1,	 -30.0,	 30.0],
                	[5,  6,	 0.0,	     0.25202,	 0.0,	 117,	 117,	 117,	 0.932,	 0.0,	 1,	 -30.0,	 30.0],
                	[6,	 11, 0.09498,	 0.1989,     0.0,	 134,	 134,	 134,	 0.0,	 0.0,	 1,	 -30.0,	 30.0],
               	    [6,	 12, 0.12291,	 0.25581,	 0.0,	 104,	 104,	 104,	 0.0,	 0.0,	 1,	 -30.0,	 30.0],
                	[6,	 13, 0.06615,	 0.13027,	 0.0,	 201,	 201,	 201,	 0.0,	 0.0,	 1,	 -30.0,	 30.0],
                	[7,	 8,	 0.0,	     0.17615,	 0.0,	 167,	 167,	 167,	 0.0,	 0.0,	 1,	 -30.0,	 30.0],
                	[7,	 9,	 0.0,	     0.11001,	 0.0,	 267,	 267,	 267,	 0.0,	 0.0,	 1,	 -30.0,	 30.0],
                	[9,	 10, 0.03181,	 0.0845,     0.0,	 325,	 325,	 325,	 0.0,	 0.0,	 1,	 -30.0,	 30.0],
                	[9,	 14, 0.12711,	 0.27038,	 0.0,	 99,	 99,	 99,	 0.0,	 0.0,	 1,	 -30.0,	 30.0],
                	[10, 11, 0.08205,	 0.19207,	 0.0,	 141,	 141,	 141,	 0.0,	 0.0,	 1,	 -30.0,	 30.0],
                	[12, 13, 0.22092,	 0.19988,	 0.0,	 99,	 99,	 99,	 0.0,	 0.0,	 1,	 -30.0,	 30.0],
                	[13, 14, 0.17093,	 0.34802,	 0.0,	 76,	 76,	 76,     0.0,	 0.0,	 1,	 -30.0,	 30.0]
                ])
}

In [4]:
bus = pd.DataFrame(net['bus'],
                   columns=['bus_i', 'type',	'Pd',	'Qd',	'Gs',	'Bs',
                            'area',	'Vm',	'Va',	'baseKV',	'zone',	'Vmax',	'Vmin'])
print(f"n_bus:{len(bus)}")
bus

n_bus:14

,bus_i,type,Pd,Qd,Gs,Bs,area,Vm,Va,baseKV,zone,Vmax,Vmin
0,1.0,3.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.06,0.94
1,2.0,2.0,21.7,12.7,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.06,0.94
2,3.0,2.0,94.2,19.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.06,0.94
3,4.0,1.0,47.8,-3.9,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.06,0.94
4,5.0,1.0,7.6,1.6,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.06,0.94
5,6.0,2.0,11.2,7.5,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.06,0.94
6,7.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.06,0.94
7,8.0,2.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.06,0.94
8,9.0,1.0,29.5,16.6,0.0,19.0,1.0,1.0,0.0,1.0,1.0,1.06,0.94
9,10.0,1.0,9.0,5.8,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.06,0.94
10,11.0,1.0,3.5,1.8,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.06,0.94
11,12.0,1.0,6.1,1.6,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.06,0.94
12,13.0,1.0,13.5,5.8,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.06,0.94
13,14.0,1.0,14.9,5.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.06,0.94

In [5]:
gen = pd.DataFrame(net['gen'],
                   columns = ['bus',	'Pg',	'Qg',
                              'Qmax',	'Qmin',	'Vg',
                              'mBase',	'status',	'Pmax',	'Pmin'])
gen

   bus     Pg    Qg  Qmax  Qmin   Vg  mBase  status   Pmax  Pmin
0  1.0  170.0   5.0  10.0   0.0  1.0  100.0     1.0  340.0   0.0
1  2.0   29.5   0.0  30.0 -30.0  1.0  100.0     1.0   59.0   0.0
2  3.0    0.0  20.0  40.0   0.0  1.0  100.0     1.0    0.0   0.0
3  6.0    0.0   9.0  24.0  -6.0  1.0  100.0     1.0    0.0   0.0
4  8.0    0.0   9.0  24.0  -6.0  1.0  100.0     1.0    0.0   0.0

In [6]:
# The bus variables indicate where the generator is connected on the grid !!!!!!

In [7]:
line = pd.DataFrame(net['branch'],
                    columns = ['fbus',	'tbus',	'r',	'x',	'b',
                               'rateA',	'rateB',	'rateC',	'ratio',
                               'angle',	'status',	'angmin',	'angmax'] )
line

,fbus,tbus,r,x,b,rateA,rateB,rateC,ratio,angle,status,angmin,angmax
0,1.0,2.0,0.01938,0.05917,0.0528,472.0,472.0,472.0,0.000,0.0,1.0,-30.0,30.0
1,1.0,5.0,0.05403,0.22304,0.0492,128.0,128.0,128.0,0.000,0.0,1.0,-30.0,30.0
2,2.0,3.0,0.04699,0.19797,0.0438,145.0,145.0,145.0,0.000,0.0,1.0,-30.0,30.0
3,2.0,4.0,0.05811,0.17632,0.0340,158.0,158.0,158.0,0.000,0.0,1.0,-30.0,30.0
4,2.0,5.0,0.05695,0.17388,0.0346,161.0,161.0,161.0,0.000,0.0,1.0,-30.0,30.0
5,3.0,4.0,0.06701,0.17103,0.0128,160.0,160.0,160.0,0.000,0.0,1.0,-30.0,30.0
6,4.0,5.0,0.01335,0.04211,0.0000,664.0,664.0,664.0,0.000,0.0,1.0,-30.0,30.0
7,4.0,7.0,0.00000,0.20912,0.0000,141.0,141.0,141.0,0.978,0.0,1.0,-30.0,30.0
8,4.0,9.0,0.00000,0.55618,0.0000,53.0,53.0,53.0,0.969,0.0,1.0,-30.0,30.0
9,5.0,6.0,0.00000,0.25202,0.0000,117.0,117.0,117.0,0.932,0.0,1.0,-30.0,30.0
10,6.0,11.0,0.09498,0.19890,0.0000,134.0,134.0,134.0,0.000,0.0,1.0,-30.0,30.0
11,6.0,12.0,0.12291,0.25581,0.0000,104.0,104.0,104.0,0.000,0.0,1.0,-30.0,30.0
12,6.0,13.0,0.06615,0.13027,0.0000,201.0,201.0,201.0,0.000,0.0,1.0,-30.0,30.0
13,7.0,8.0,0.00000,0.17615,0.0000,167.0,167.0,167.0,0.000,0.0,1.0,-30.0,30.0
14,7.0,9.0,0.00000,0.11001,0.0000,267.0,267.0,267.0,0.000,0.0,1.0,-30.0,30.0
15,9.0,10.0,0.03181,0.08450,0.0000,325.0,325.0,325.0,0.000,0.0,1.0,-30.0,30.0
16,9.0,14.0,0.12711,0.27038,0.0000,99.0,99.0,99.0,0.000,0.0,1.0,-30.0,30.0
17,10.0,11.0,0.08205,0.19207,0.0000,141.0,141.0,141.0,0.000,0.0,1.0,-30.0,30.0
18,12.0,13.0,0.22092,0.19988,0.0000,99.0,99.0,99.0,0.000,0.0,1.0,-30.0,30.0
19,13.0,14.0,0.17093,0.34802,0.0000,76.0,76.0,76.0,0.000,0.0,1.0,-30.0,30.0

In [8]:
# lines connecting from_bus to to_bus with some specific parameters, e.g. resistance (r) and reactance (x).

In [9]:
gen_cost = pd.DataFrame(net['gencost'],
                        columns = ['order_poly', 'startup', 'shutdown', 'num_coefficient', 'c2', 'c1', 'c0'])
gen_cost

   order_poly  startup  shutdown  num_coefficient   c2         c1   c0
0         2.0      0.0       0.0              3.0  0.0   7.920951  0.0
1         2.0      0.0       0.0              3.0  0.0  23.269494  0.0
2         2.0      0.0       0.0              3.0  0.0   0.000000  0.0
3         2.0      0.0       0.0              3.0  0.0   0.000000  0.0
4         2.0      0.0       0.0              3.0  0.0   0.000000  0.0

In [10]:
# First, we use PyPower to solve the complex AC-OPF problem

In [11]:
#! pip install pyrlu

# Machine learning for AC-OPF

In [12]:
"""================================Training Data Generation================================"""

'================================Training Data Generation================================'

In [13]:
from pypower import idx_bus, idx_gen, idx_brch
from tqdm import tqdm

# Data exploration

In [14]:
df = pd.read_csv('./data/pglib_opf_case5_pjm.csv')
df.head()

,load1:pl,load2:pl,load3:pl,load1:ql,load2:ql,load3:ql,gen1:pg,gen2:pg,gen3:pg,gen4:pg,...,line3:p_fr_max,line4:p_fr_max,line5:p_fr_max,line6:p_fr_max,line1:q_fr_max,line2:q_fr_max,line3:q_fr_max,line4:q_fr_max,line5:q_fr_max,line6:q_fr_max
0,6.570765,2.275993,4.051883,4.376283,0.628149,4.026378,0.4,1.7,4.876424,1.558644,...,-0.000002,-0.000003,-2.720498e-07,-0.000006,0.000000e+00,0.0,-7.933284e-07,-1.873404e-06,0.0,-3.069352e-06
1,6.552550,1.704638,4.090173,4.400894,0.724693,3.937011,0.4,1.7,4.317437,1.531758,...,-0.000002,-0.000003,-2.624331e-07,-0.000006,0.000000e+00,0.0,-7.848656e-07,-1.892890e-06,0.0,-2.936123e-06
2,5.645406,2.029723,5.955067,1.377338,0.865517,3.240306,0.4,1.7,5.199999,1.490930,...,-0.000002,-0.000002,0.000000e+00,-0.000280,-1.365476e-07,0.0,0.000000e+00,-8.479213e-07,0.0,-3.177477e-07
3,4.778645,2.417017,6.361179,0.843277,0.881531,2.635903,0.4,1.7,5.200000,1.644658,...,-0.000001,-0.000001,0.000000e+00,-0.647117,-3.141235e-07,0.0,0.000000e+00,-7.238938e-07,0.0,-6.550166e-09
4,5.690040,2.458801,5.745494,2.003454,1.119158,3.286294,0.4,1.7,5.200000,1.684051,...,-0.000002,-0.000002,-5.028490e-09,-0.000067,0.000000e+00,0.0,0.000000e+00,-9.201327e-07,0.0,-6.686726e-07

In [15]:
df.shape

(10000, 104)

In [16]:
df.columns

Index(['load1:pl', 'load2:pl', 'load3:pl', 'load1:ql', 'load2:ql', 'load3:ql',
       'gen1:pg', 'gen2:pg', 'gen3:pg', 'gen4:pg',
       ...
       'line3:p_fr_max', 'line4:p_fr_max', 'line5:p_fr_max', 'line6:p_fr_max',
       'line1:q_fr_max', 'line2:q_fr_max', 'line3:q_fr_max', 'line4:q_fr_max',
       'line5:q_fr_max', 'line6:q_fr_max'],
      dtype='object', length=104)

In [17]:
""" We can see that this is dataset of 10000 rows by 104 columns.
    Each row represents the feature and solution of the AC-OPF.
    Let's define the inputs and outputs for the machine learning based on the AC-OPF formulation we have learned.
"""

" We can see that this is dataset of 10000 rows by 104 columns.\n    Each row represents the feature and solution of the AC-OPF.\n    Let's define the inputs and outputs for the machine learning based on the AC-OPF formulation we have learned.\n"

In [18]:
""" For example, columns 0:3 represents the active power consumption for the loads, while comlumns 3:6 represent the reactive power consumption of the loads.
    We can now separete them into a variable called "input", which means they are the input parameters for the AC-OPF problem.
"""

' For example, columns 0:3 represents the active power consumption for the loads, while comlumns 3:6 represent the reactive power consumption of the loads.\n    We can now separete them into a variable called "input", which means they are the input parameters for the AC-OPF problem.\n'

In [19]:
# define input columns

load_p = list(df.columns[0:3])
load_q = list(df.columns[3:6])
inputs = load_p + load_q
print(inputs)

['load1:pl', 'load2:pl', 'load3:pl', 'load1:ql', 'load2:ql', 'load3:ql']

In [20]:
""" We can do the same with the outputs, the optimal solution for the AC-OPF problem given load demand,
    which includes the active and reactive power at each generator as well as the voltage magnitude and angle at each bus.
"""

' We can do the same with the outputs, the optimal solution for the AC-OPF problem given load demand,\n    which includes the active and reactive power at each generator as well as the voltage magnitude and angle at each bus.\n'

In [21]:
# Define output columns

gen_p = list(df.columns[6:11])
gen_q = list(df.columns[11:16])

In [22]:
gen_p

['gen1:pg', 'gen2:pg', 'gen3:pg', 'gen4:pg', 'gen5:pg']

In [23]:
def convert(x):
    #Remove spaces around the '+' or '-' before 'j'
    x = x.replace(" + ", "+").replace(" - ", "-").replace(" j ", "j").strip()
    return np.complex64(x)

In [24]:
df.columns[21:26]

Index(['bus1:v_bus', 'bus2:v_bus', 'bus3:v_bus', 'bus4:v_bus', 'bus5:v_bus'], dtype='object')

In [25]:
bus_vm = []
bus_va = []
for bus_v_column in df.columns[21:26]:
    df[bus_v_column + '_mag'] = df[bus_v_column].apply(convert).apply(np.abs)
    bus_vm.append(bus_v_column + '_mag')
    
    df[bus_v_column + '_ang'] = df[bus_v_column].apply(convert).apply(np.angle)
    ## the follow line of code is to correct a bug in the OPFLearn dataset
    df[bus_v_column + '_ang'] = -1*np.rad2deg(df[bus_v_column + '_ang'].values)
    bus_va.append(bus_v_column + '_ang')
    
outputs = gen_p + gen_q + bus_vm + bus_va
print(outputs)

['gen1:pg', 'gen2:pg', 'gen3:pg', 'gen4:pg', 'gen5:pg', 'gen1:qg', 'gen2:qg', 'gen3:qg', 'gen4:qg', 'gen5:qg', 'bus1:v_bus_mag', 'bus2:v_bus_mag', 'bus3:v_bus_mag', 'bus4:v_bus_mag', 'bus5:v_bus_mag', 'bus1:v_bus_ang', 'bus2:v_bus_ang', 'bus3:v_bus_ang', 'bus4:v_bus_ang', 'bus5:v_bus_ang']

In [26]:
df

,load1:pl,load2:pl,load3:pl,load1:ql,load2:ql,load3:ql,gen1:pg,gen2:pg,gen3:pg,gen4:pg,...,bus1:v_bus_mag,bus1:v_bus_ang,bus2:v_bus_mag,bus2:v_bus_ang,bus3:v_bus_mag,bus3:v_bus_ang,bus4:v_bus_mag,bus4:v_bus_ang,bus5:v_bus_mag,bus5:v_bus_ang
0,6.570765,2.275993,4.051883,4.376283,0.628149,4.026378,0.4,1.7,4.876424,1.558644e+00,...,1.088747,0.031466,1.027343,-0.047701,1.058290,-0.018030,1.055571,-1.044813e-31,1.100000,0.044278
1,6.552550,1.704638,4.090173,4.400894,0.724693,3.937011,0.4,1.7,4.317437,1.531758e+00,...,1.088817,0.032032,1.027087,-0.046907,1.058152,-0.017335,1.056337,-7.842915e-32,1.100000,0.044911
2,5.645406,2.029723,5.955067,1.377338,0.865517,3.240306,0.4,1.7,5.199999,1.490930e+00,...,1.081929,0.046786,1.080142,-0.020623,1.100000,0.003993,1.064614,-4.099984e-33,1.076183,0.061261
3,4.778645,2.417017,6.361179,0.843277,0.881531,2.635903,0.4,1.7,5.200000,1.644658e+00,...,1.073330,0.049556,1.082470,-0.011662,1.100000,0.007987,1.059389,3.173137e-36,1.064221,0.063242
4,5.690040,2.458801,5.745494,2.003454,1.119158,3.286294,0.4,1.7,5.200000,1.684051e+00,...,1.095219,0.043703,1.079232,-0.025925,1.100000,-0.002590,1.075028,2.562954e-33,1.093446,0.058019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,4.254369,4.712440,4.836094,2.668600,3.629953,1.640128,0.4,1.7,5.200000,1.622811e+00,...,1.093770,0.042283,1.039607,-0.028559,1.051908,-0.017452,1.076681,-8.360963e-35,1.100000,0.055911
9996,3.210700,1.671734,4.661965,1.612852,0.490558,2.501960,0.4,1.7,3.086005,1.944606e-07,...,1.075134,0.050848,1.078772,-0.002335,1.100000,0.005464,1.062197,3.296830e-36,1.066963,0.062918
9997,4.979303,3.477785,4.071830,2.229018,3.314802,2.390931,0.4,1.7,5.200000,5.078266e-01,...,1.094907,0.041556,1.049922,-0.026832,1.061713,-0.007820,1.073106,4.240605e-34,1.100000,0.054636
9998,2.047435,5.546288,4.167393,0.539519,4.802855,0.740298,0.4,1.7,5.200000,7.091980e-02,...,1.100000,0.048322,1.074188,-0.002144,1.072140,-0.003328,1.092085,2.087602e-34,1.097649,0.059401
9999,2.421045,3.904998,3.945988,1.049075,0.312827,2.118950,0.4,1.7,3.586479,1.057364e-07,...,1.068940,0.050141,1.081619,-0.010822,1.100000,-0.012539,1.054228,1.371935e-34,1.059144,0.063849

In [27]:
""" Take a look into each of those columns.
    The following function plots the histogram of each variable, so it takes the whole 10000 samples for each variable and plots the distribution.
    On the x-axis we see the variable value and on the y-axis the frequency of samples that fit into a specific bucket or bin.
    We will be using 10 bins just to get an idea of the shape of the distribution.
    Notice that we are also annotating the mean of all the samples in black.
"""

' Take a look into each of those columns.\n    The following function plots the histogram of each variable, so it takes the whole 10000 samples for each variable and plots the distribution.\n    On the x-axis we see the variable value and on the y-axis the frequency of samples that fit into a specific bucket or bin.\n    We will be using 10 bins just to get an idea of the shape of the distribution.\n    Notice that we are also annotating the mean of all the samples in black.\n'

In [28]:
""" We can see that generators'setpoints are set always at the same level most of the time.
    Notice that some generators are generating "negative" reactive power.
    This mean, by convention, that sometimes these generators are consuming reactive power instead of generating.
    In the case of voltage magnitude, it is very constant around the mean with a few samples below that level.
    This is expected as the voltage magnitude values are constrained by the AC-OPF problem.
"""

' We can see that generators\'setpoints are set always at the same level most of the time.\n    Notice that some generators are generating "negative" reactive power.\n    This mean, by convention, that sometimes these generators are consuming reactive power instead of generating.\n    In the case of voltage magnitude, it is very constant around the mean with a few samples below that level.\n    This is expected as the voltage magnitude values are constrained by the AC-OPF problem.\n'

# Case Study: Traditional Machine learning for Solving AC-OPF

In [29]:
torch.cuda.is_available()
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"=======Using {device} device==========")

=======Using cuda device==========

In [30]:
class OPFDataset(Dataset):
    def __init__(self, data, inputs, outputs):
        self.data = data
        self.inputs = inputs
        self.outputs = outputs
    
    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        input = torch.tensor(self.data.iloc[idx,:len(self.inputs)].values).to(torch.float32)
        output = torch.tensor(self.data.iloc[idx, len(self.inputs):].values).to(torch.float32)

        return input, output

In [31]:
data = df[inputs + outputs]
train_data = data.sample(frac=0.8, random_state=SEED)
test_data = data.drop(train_data.index)

In [32]:
train_dataloader = DataLoader(OPFDataset(train_data, inputs, outputs),
                             batch_size=32, shuffle=True)
test_dataloader = DataLoader(OPFDataset(test_data, inputs, outputs),
                            batch_size=32, shuffle=False)

# Evaluation Metric for AC-OPF

In [33]:
""" We have a trained model to "solve" AC-OPF, which predicts the power generation and bus voltage values given the electricity load demand.
    We use a mean squared error (MSE) loss function to train the NN model and evaluate it on the test dataset.
    ----------------------------------Butttttt, HOW DO WE KNOW THE NN IS GOOD ENOUGH TO SOLVE AC-OPF ?-------------------------------------
    General, we care about three metrics:
    1. Feasibility: The solution needs to satisfy the equality & inequality constraints of the optimization problem.
    2. Optimaly: The feasibile solution incurs the lowest cost compared with all other feasible solutions.
    3. Run-time complexity: We solve the problem fast.
"""

' We have a trained model to "solve" AC-OPF, which predicts the power generation and bus voltage values given the electricity load demand.\n    We use a mean squared error (MSE) loss function to train the NN model and evaluate it on the test dataset.\n    ----------------------------------Butttttt, HOW DO WE KNOW THE NN IS GOOD ENOUGH TO SOLVE AC-OPF ?-------------------------------------\n    General, we care about three metrics:\n    1. Feasibility: The solution needs to satisfy the equality & inequality constraints of the optimization problem.\n    2. Optimaly: The feasibile solution incurs the lowest cost compared with all other feasible solutions.\n    3. Run-time complexity: We solve the problem fast.\n'

In [34]:
batch_snapshot = next(iter(test_dataloader))
snapshot_x, snapshot_y = batch_snapshot[0][[0]], batch_snapshot[1][[0]]

#  Solution quality

In [35]:
 """ ==============================Prepare dataset=========================== """

if not os.path.exists('./data/pglib_opf_case5_pjm.csv'):
    ! mkdir data
    ! wget https://data.nrel.gov/system/files/177/pglib_opf_case5_pjm.csv -P data/

df = pd.read_csv('./data/pglib_opf_case5_pjm.csv')

df

,load1:pl,load2:pl,load3:pl,load1:ql,load2:ql,load3:ql,gen1:pg,gen2:pg,gen3:pg,gen4:pg,...,line3:p_fr_max,line4:p_fr_max,line5:p_fr_max,line6:p_fr_max,line1:q_fr_max,line2:q_fr_max,line3:q_fr_max,line4:q_fr_max,line5:q_fr_max,line6:q_fr_max
0,6.570765,2.275993,4.051883,4.376283,0.628149,4.026378,0.4,1.7,4.876424,1.558644e+00,...,-0.000002,-3.158833e-06,-2.720498e-07,-0.000006,0.000000e+00,0.0,-7.933284e-07,-1.873404e-06,0.000000e+00,-3.069352e-06
1,6.552550,1.704638,4.090173,4.400894,0.724693,3.937011,0.4,1.7,4.317437,1.531758e+00,...,-0.000002,-3.122458e-06,-2.624331e-07,-0.000006,0.000000e+00,0.0,-7.848656e-07,-1.892890e-06,0.000000e+00,-2.936123e-06
2,5.645406,2.029723,5.955067,1.377338,0.865517,3.240306,0.4,1.7,5.199999,1.490930e+00,...,-0.000002,-2.135219e-06,0.000000e+00,-0.000280,-1.365476e-07,0.0,0.000000e+00,-8.479213e-07,0.000000e+00,-3.177477e-07
3,4.778645,2.417017,6.361179,0.843277,0.881531,2.635903,0.4,1.7,5.200000,1.644658e+00,...,-0.000001,-1.325614e-06,0.000000e+00,-0.647117,-3.141235e-07,0.0,0.000000e+00,-7.238938e-07,0.000000e+00,-6.550166e-09
4,5.690040,2.458801,5.745494,2.003454,1.119158,3.286294,0.4,1.7,5.200000,1.684051e+00,...,-0.000002,-1.892448e-06,-5.028490e-09,-0.000067,0.000000e+00,0.0,0.000000e+00,-9.201327e-07,0.000000e+00,-6.686726e-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,4.254369,4.712440,4.836094,2.668600,3.629953,1.640128,0.4,1.7,5.200000,1.622811e+00,...,-0.000002,-5.391748e-07,-3.094541e-07,-0.000035,0.000000e+00,0.0,-3.345210e-07,-4.580856e-07,-3.435519e-07,-9.531376e-07
9996,3.210700,1.671734,4.661965,1.612852,0.490558,2.501960,0.4,1.7,3.086005,1.944606e-07,...,-0.000001,-4.541733e-07,0.000000e+00,-2.080116,-1.879487e-07,0.0,0.000000e+00,-1.067423e-06,0.000000e+00,-3.644367e-09
9997,4.979303,3.477785,4.071830,2.229018,3.314802,2.390931,0.4,1.7,5.200000,5.078266e-01,...,-0.000002,-1.077054e-06,-1.362549e-07,-0.000024,0.000000e+00,0.0,-2.538087e-07,-4.059619e-07,-1.515269e-07,-1.182981e-06
9998,2.047435,5.546288,4.167393,0.539519,4.802855,0.740298,0.4,1.7,5.200000,7.091980e-02,...,-0.000001,0.000000e+00,-8.133506e-08,-0.016308,0.000000e+00,0.0,0.000000e+00,0.000000e+00,-2.923717e-07,-4.133202e-08
9999,2.421045,3.904998,3.945988,1.049075,0.312827,2.118950,0.4,1.7,3.586479,1.057364e-07,...,-0.000001,0.000000e+00,-1.306598e-07,-0.275335,-3.803464e-07,0.0,0.000000e+00,-9.219739e-07,0.000000e+00,-1.012086e-08

In [36]:
def convert(x):
    #Remove spaces around the '+' or '-' before 'j'
    x = x.replace(" + ", "+").replace(" - ", "-").replace(" j ", "j").strip()
    return np.complex64(x)

In [37]:
""" Define input and output columns"""

load_p = list(df.columns[0:3])
load_q = list(df.columns[3:6])
inputs = load_p + load_q
print(f"Input includes {inputs}\n")

gen_p = list(df.columns[6:11])
gen_q = list(df.columns[11:16])
bus_vm = []
bus_va = []
v_bus = df.columns[21:26]
for bus_v_column in v_bus:
    df[bus_v_column + '_mag'] = df[bus_v_column].apply(convert).apply(np.abs)
    bus_vm.append(bus_v_column + '_mag')
    df[bus_v_column + '_ang'] = df[bus_v_column].apply(convert).apply(np.angle)
    df[bus_v_column + '_ang'] = -1*np.rad2deg(df[bus_v_column + '_ang'].values)
    bus_va.append(bus_v_column + '_ang')
outputs = gen_p + gen_q + bus_vm + bus_va
print(f"Output includes {outputs}\n")

Input includes ['load1:pl', 'load2:pl', 'load3:pl', 'load1:ql', 'load2:ql', 'load3:ql']

Output includes ['gen1:pg', 'gen2:pg', 'gen3:pg', 'gen4:pg', 'gen5:pg', 'gen1:qg', 'gen2:qg', 'gen3:qg', 'gen4:qg', 'gen5:qg', 'bus1:v_bus_mag', 'bus2:v_bus_mag', 'bus3:v_bus_mag', 'bus4:v_bus_mag', 'bus5:v_bus_mag', 'bus1:v_bus_ang', 'bus2:v_bus_ang', 'bus3:v_bus_ang', 'bus4:v_bus_ang', 'bus5:v_bus_ang']

In [38]:
""" Custom dataset"""

class OPFDataset(Dataset):
    def __init__(self, data, inputs, outputs):
        self.data = data
        self.inputs = inputs
        self.outputs = outputs
    
    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        input = torch.tensor(self.data.iloc[idx,:len(self.inputs)].values).to(torch.float32)
        output = torch.tensor(self.data.iloc[idx, len(self.inputs):].values).to(torch.float32)
        return input, output

In [39]:
data = df[inputs + outputs]
train_data = data.sample(frac=0.8, random_state=SEED)
test_data = data.drop(train_data.index)
train_data_loader = DataLoader(OPFDataset(train_data, inputs, outputs),
                              batch_size=32, shuffle=True)
test_data_loader  = DataLoader(OPFDataset(test_data, inputs, outputs),
                              batch_size=32, shuffle=False)

# Define the evaluation metric as we did in the discussion

In [40]:
from pypower.api import makeYbus, ext2int

In [41]:
class OPF_metric():
    def __init__(self, net):
        basemva = net['baseMVA']
        linear_cost = net['gencost'][:,5]
        self.cost_coef = torch.tensor(linear_cost).to(torch.float32)

        pg_max = net['gen'][:, idx_gen.PMAX] / basemva
        pg_min = net['gen'][:, idx_gen.PMIN] / basemva
        qg_max = net['gen'][:, idx_gen.QMAX] / basemva
        qg_min = net['gen'][:, idx_gen.QMIN] / basemva
        vm_max = net['bus'][:, idx_bus.VMAX]
        vm_min = net['bus'][:, idx_bus.VMIN]
        va_max = [np.pi/2 for i in range(len(net['bus']))]
        va_min = [-np.pi/2 for i in range(len(net['bus']))]
        outputs_min = np.concatenate([pg_min, qg_min, vm_min, va_min])
        outputs_max = np.concatenate([pg_max, qg_max, vm_max, va_max])
        self.outputs_min = torch.as_tensor(outputs_min).to(torch.float32).view(1,-1)
        self.outputs_max = torch.as_tensor(outputs_max).to(torch.float32).view(1,-1)

        # ============= Calculate the bus admittance matrix (Ybus) and branch admittance matrices (Yf, Yt) ============#
        net = ext2int(net)
        Ybus, Yf, Yt = makeYbus(net['baseMVA'], net['bus'], net['branch'])
        Ybus = Ybus.todense()
        self.Ybus_real = torch.as_tensor(Ybus.real).to(torch.float32)
        self.Ybus_imag = torch.as_tensor(Ybus.imag).to(torch.float32)
        Yf = Yf.todense()
        Yt = Yt.todense()
        self.Yf_real = torch.as_tensor(Yf.real).to(torch.float32)
        self.Yf_imag = torch.as_tensor(Yf.imag).to(torch.float32)
        self.Yt_real = torch.as_tensor(Yt.real).to(torch.float32)
        self.Yt_imag = torch.as_tensor(Yt.imag).to(torch.float32)

        self.gen_bus_index = net['gen'][:,idx_gen.GEN_BUS]
        self.load_bus_index = [i for i in range(5) if net['bus'][i, idx_bus.PD]>0]

        self.fbus = net['branch'][:,idx_brch.F_BUS].astype(int)
        self.tbus = net['branch'][:,idx_brch.T_BUS].astype(int)
        self.smax = torch.as_tensor(net['branch'][:,idx_brch.RATE_A] / basemva).to(torch.float32)
        self.angmax = torch.as_tensor(np.deg2rad(net['branch'][:,idx_brch.ANGMAX])).to(torch.float32)

    # Let's find the generation cost
    def cal_gen_cost(self, outputs):
        device = outputs.device  # Get the device of the outputs tensor
        cost_coef = self.cost_coef.to(device)
        pg = outputs[:, :5]
        return (pg  * cost_coef).sum(1)

    def cal_upper_lower_bound_violation(self, outputs):
        device = outputs.device  # Get the device of the outputs tensor
        outputs_max = self.outputs_max.to(device)  # Move to the same device
        outputs_min = self.outputs_min.to(device)  # Move to the same device
    
        # Use the local variables outputs_max and outputs_min
        vio_1 = torch.relu(outputs - outputs_max)
        vio_2 = torch.relu(outputs_min - outputs)
        return vio_1 + vio_2

    def gen_load_to_bus(self, inputs, outputs):
        device = outputs.device
        batch = inputs.shape[0]
        pd = inputs[:, :3]
        qd = inputs[:, 3:]
        pg = outputs[:, 0:5]
        qg = outputs[:, 5:10]
        bus_pg = torch.zeros([batch, 5], device=device)
        bus_qg = torch.zeros([batch, 5], device=device)
        for i, bus_index in enumerate(self.gen_bus_index):
            bus_pg[:, int(bus_index)] = bus_pg[:, int(bus_index)] + pg[:, i]
            bus_qg[:, int(bus_index)] = bus_qg[:, int(bus_index)] + qg[:, i]
        bus_pd = torch.zeros([batch, 5], device=device)
        bus_qd = torch.zeros([batch, 5], device=device)
        for i, bus_index in enumerate(self.load_bus_index):

            bus_pd[:, bus_index] = bus_pd[:, bus_index] + pd[:, i]
            bus_qd[:, bus_index] = bus_qd[:, bus_index] + qd[:, i]
        return bus_pg, bus_qg, bus_pd, bus_qd

    def cal_power_balance_violation(self, inputs, outputs):
        device = outputs.device 
        bus_pg, bus_qg, bus_pd, bus_qd = self.gen_load_to_bus(inputs, outputs)
        bus_p_inj = bus_pg - bus_pd
        bus_q_inj = bus_qg - bus_qd
        
        vm, va = outputs[:, 10:15], outputs[:, 15:20]
        vr = vm * torch.cos(va)
        vi = vm * torch.sin(va)
        
        self.Ybus_real = self.Ybus_real.to(device)
        self.Ybus_imag = self.Ybus_imag.to(device)

        Ir = torch.matmul(vr, self.Ybus_real) - vi @ self.Ybus_imag
        Ii = vi @ self.Ybus_real + vr @ self.Ybus_imag
        bus_p = (vr * Ir) + (vi * Ii)
        bus_q = (vi * Ir) - (vr * Ii)
        return torch.abs(bus_p_inj - bus_p), torch.abs(bus_q_inj - bus_q)

    # Let's calculate the branch flow & angle constraint violation
    def cal_branch_flow_vio(self, outputs):
        device = outputs.device 
        vm, va = outputs[:, 10:15], outputs[:, 15:20]
        vr = vm * torch.cos(va)
        vi = vm * torch.sin(va)
        
        self.Yf_real = self.Yf_real.to(device)
        self.Yf_imag = self.Yf_imag.to(device)
        self.Yt_real = self.Yt_real.to(device)
        self.Yt_imag = self.Yt_imag.to(device)
        self.smax = self.smax.to(device)
        self.angmax = self.angmax.to(device)
        
        Irf = vr @ self.Yf_real.T - vi @ self.Yf_imag.T
        Iif = vi @ self.Yf_real.T + vr @ self.Yf_imag.T
        branch_pf = vr[:, self.fbus] * Irf + vi[:, self.fbus] * Iif
        branch_qf = vi[:, self.fbus] * Irf - vr[:, self.fbus] * Iif
        sf = torch.sqrt((torch.square(branch_pf) + torch.square(branch_qf)))

        Irt = vr @ self.Yt_real.T - vi @ self.Yt_imag.T
        Iit = vi @ self.Yt_real.T + vr @ self.Yt_imag.T
        branch_pf = vr[:, self.tbus] * Irt + vi[:, self.tbus] * Iit
        branch_qf = vi[:, self.tbus] * Irt - vr[:, self.tbus] * Iit
        st = torch.sqrt((torch.square(branch_pf) + torch.square(branch_qf)))

        branch_flow = torch.maximum(sf, st)
        branch_ang = torch.abs(va[:, self.fbus] - va[:, self.tbus])
        return torch.relu(branch_flow - self.smax), torch.relu(branch_ang - self.angmax)

In [42]:
opf_metric = OPF_metric(net)

In [43]:
def test(dataloader, model, opf_metric):
    device = next(model.parameters()).device
    batch_snapshot = next(iter(dataloader))
    X, Y = batch_snapshot[0].to(device), batch_snapshot[1].to(device)
    with torch.no_grad():
      Y_pred = model(X)

    test_sol_mse = ((Y_pred - Y)**2)

    Y_pred_cost = opf_metric.cal_gen_cost(Y_pred)
    Y_opt_cost = opf_metric.cal_gen_cost(Y)
    test_obj_gap = (Y_pred_cost - Y_opt_cost)/Y_opt_cost

    vio_bound = opf_metric.cal_upper_lower_bound_violation(Y_pred)
    vio_p_mis, vio_q_mis = opf_metric.cal_power_balance_violation(X, Y_pred)
    vio_flow, vio_ang = opf_metric.cal_branch_flow_vio(Y_pred)
    eq_vio = torch.cat([vio_p_mis, vio_q_mis], dim=1)
    ineq_vio = torch.cat([vio_bound, vio_flow, vio_ang], dim=1)
    return test_sol_mse, test_obj_gap, eq_vio, ineq_vio

def model_train_test(train_dataloader, test_dataloader, model,
                     loss_fn, opf_metric, epochs = 10, penalty=False):
    torch.manual_seed(2024)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.0005)
    results = {
        "train_losses": [],
        "test_mse": [],
        "opt_gaps": [],
        "eq_vios": [],
        "ineq_vios": []
    }
    print(f"==============================================Start training on {device}===========================================")

    for t in range(epochs):
        model.train()
        train_loss = []
        with torch.enable_grad():
            for batch, (X, y) in enumerate(train_dataloader):
                X, y = X.to(device), y.to(device)
                # Compute prediction error
                pred = model(X)
                if penalty:
                  loss = loss_fn(X, pred, y)
                else:
                  loss = loss_fn(pred, y)
                # Backpropagation
                loss.backward()
                optimizer.step()
                optimizer.zero_grad()
                train_loss.append(loss.item())
            train_loss = np.mean(train_loss)
            results["train_losses"].append(train_loss)
            test_sol_mse, test_obj_gap, eq_vio, ineq_vio = test(test_dataloader, model, opf_metric)
            
            results["test_mse"].append(test_sol_mse)
            results["opt_gaps"].append(test_obj_gap)
            results["eq_vios"].append(eq_vio)
            results["ineq_vios"].append(ineq_vio)
            
            print(f"Epoch {t+1} | Train loss: {train_loss:.7f} | ",
                f"Test mse: {test_sol_mse.mean():.7f} | ",
                f"opt gap: {test_obj_gap.mean():.7f}% | ",
                f"eq vio: {eq_vio.sum(1).mean():.7f} | ",
                f"ineq vio: {ineq_vio.sum(1).mean():.7f} |")
        
    return results

# ResNet

In [44]:
class residual_layer(nn.Module):
    def __init__(self, in_dim, outdim):
        super().__init__()
        """
        define a residual layer
        """
        self.layer = nn.Sequential(nn.Linear(in_dim, in_dim//2),
                                  nn.ReLU(),
                                  nn.Linear(in_dim//2,in_dim))
    def forward(self, x):
        return self.layer(x) + x


class ResidualNeuralNetwork(nn.Module):
    def __init__(self, x_size=3, y_size=5, width=32, depth=3):
        super().__init__()
        NN = [nn.Linear(x_size, width)]
        for _ in range(depth):
            NN.append(residual_layer(width, width))
        NN.append(nn.Linear(width, y_size))
        self.NN = nn.Sequential(*NN)
    def forward(self, x):
        y = self.NN(x)
        return y

# Enforcing Physical Limits

In [45]:
""" Let's add the violatio into loss function and minimize it
"""
class MSEPenaltyLoss(nn.Module):
    def __init__(self, opf_metric, w_eq=0.1, w_ineq=0.1):
        super().__init__()
        self.w_eq = w_eq
        self.w_ineq = w_ineq
        self.mse = nn.MSELoss()
        self.opf_metric = opf_metric

    def forward(self, X, pred, target):
        MSE = self.mse(pred, target)
        
        vio_bound = self.opf_metric.cal_upper_lower_bound_violation(pred)
        vio_p_mis, vio_q_mis = self.opf_metric.cal_power_balance_violation(X, pred)
        vio_flow, vio_ang = self.opf_metric.cal_branch_flow_vio(pred)

        eq_vio = torch.cat([vio_p_mis, vio_q_mis], dim=1)
        ineq_vio = torch.cat([vio_bound, vio_flow, vio_ang], dim=1)

        loss = MSE + self.w_eq * eq_vio.mean() + self.w_ineq * ineq_vio.mean()
        return loss

In [46]:
""" AC-OPF solutions must respect operational constraints
        - voltage levels
        - power flow litmits
    which are essential for maintaining the physical and safety standards of power systems.
    We will try to implement different approaches to enfore the physical limits of AC-OPF
        1. Upper/Lower Bound Constraint: 
          - Use the sigmoid activation function and scaling operations to enforce simple upper and lower bounds.
        2. Non-linear Equality and Inequality Constraints:
          - Improve feasibility by intergrating penalty functions into the loss function.
          - Adjust the penalty weights to enhance model performance and constraint adherence
"""

' AC-OPF solutions must respect operational constraints\n        - voltage levels\n        - power flow litmits\n    which are essential for maintaining the physical and safety standards of power systems.\n    We will try to implement different approaches to enfore the physical limits of AC-OPF\n        1. Upper/Lower Bound Constraint: \n          - Use the sigmoid activation function and scaling operations to enforce simple upper and lower bounds.\n        2. Non-linear Equality and Inequality Constraints:\n          - Improve feasibility by intergrating penalty functions into the loss function.\n          - Adjust the penalty weights to enhance model performance and constraint adherence\n'

In [47]:
""" Suppose we have the upper/lower bound information for the decision varibale.
    Let's try to get the NN to enforce the bound. This involves two steps:
        1. Using sigmoid function on the output, to make it within [0, 1]
        2. Using affine transformation to make the [0, 1] output to the corresponding [I,u]
"""

" Suppose we have the upper/lower bound information for the decision varibale.\n    Let's try to get the NN to enforce the bound. This involves two steps:\n        1. Using sigmoid function on the output, to make it within [0, 1]\n        2. Using affine transformation to make the [0, 1] output to the corresponding [I,u]\n"

# ResNet

In [48]:
class BoundNeuralNetwork(ResidualNeuralNetwork):
    def __init__(self, x_size, y_size, width, depth, yl, yu):
        super().__init__(x_size, y_size, width, depth)
 
                # Store bounds as buffers for consistency across devices
        self.register_buffer('yl', torch.tensor(yl, dtype=torch.float32))
        self.register_buffer('yu', torch.tensor(yu, dtype=torch.float32))
    def forward(self, x):
        y = self.NN(x)
        y = torch.sigmoid(y)
        y = y * (self.yu - self.yl) + self.yl
        return y

In [49]:
model_bound = BoundNeuralNetwork(x_size=len(inputs),
                                y_size=len(outputs),
                                width=64,
                                depth=6,
                                yl=opf_metric.outputs_min,
                                yu=opf_metric.outputs_max,
                                ).to(device)

/tmp/ipykernel_15893/4289910525.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.register_buffer('yl', torch.tensor(yl, dtype=torch.float32))
/tmp/ipykernel_15893/4289910525.py:7: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.register_buffer('yu', torch.tensor(yu, dtype=torch.float32))

In [50]:
result2 = model_train_test(train_data_loader, test_data_loader, model_bound, MSEPenaltyLoss(opf_metric),opf_metric, epochs=50, penalty=True)

==============================================Start training on cuda===========================================
Epoch 1 | Train loss: 1.0253067 |  Test mse: 0.1729798 |  opt gap: 0.0265084% |  eq vio: 24.6351624 |  ineq vio: 0.6883281 |
Epoch 2 | Train loss: 0.3101340 |  Test mse: 0.1527106 |  opt gap: 0.0256341% |  eq vio: 13.0952320 |  ineq vio: 0.0725400 |
Epoch 3 | Train loss: 0.2630629 |  Test mse: 0.1460355 |  opt gap: 0.0260687% |  eq vio: 8.7753563 |  ineq vio: 0.3406026 |
Epoch 4 | Train loss: 0.2414360 |  Test mse: 0.1345419 |  opt gap: 0.0181786% |  eq vio: 12.1189709 |  ineq vio: 0.8485147 |
Epoch 5 | Train loss: 0.2198617 |  Test mse: 0.1252365 |  opt gap: 0.0087278% |  eq vio: 6.2302494 |  ineq vio: 0.4768497 |
Epoch 6 | Train loss: 0.2078988 |  Test mse: 0.1116590 |  opt gap: 0.0093311% |  eq vio: 14.6014652 |  ineq vio: 3.0181298 |
Epoch 7 | Train loss: 0.1881244 |  Test mse: 0.0975623 |  opt gap: 0.0065881% |  eq vio: 6.7103801 |  ineq vio: 0.3134676 |
Epoch 8 | Train loss: 0.1628584 |  Test mse: 0.0849371 |  opt gap: 0.0106006% |  eq vio: 6.0712500 |  ineq vio: 0.7443846 |
Epoch 9 | Train loss: 0.1460514 |  Test mse: 0.0783748 |  opt gap: 0.0000386% |  eq vio: 9.5963545 |  ineq vio: 0.1005863 |
Epoch 10 | Train loss: 0.1433304 |  Test mse: 0.0730313 |  opt gap: -0.0007500% |  eq vio: 8.3698826 |  ineq vio: 1.1750119 |
Epoch 11 | Train loss: 0.1328928 |  Test mse: 0.0677333 |  opt gap: 0.0095191% |  eq vio: 6.7487292 |  ineq vio: 0.7406090 |
Epoch 12 | Train loss: 0.1213977 |  Test mse: 0.0671838 |  opt gap: 0.0003007% |  eq vio: 9.4000912 |  ineq vio: 0.6295902 |
Epoch 13 | Train loss: 0.1251493 |  Test mse: 0.0619838 |  opt gap: -0.0018079% |  eq vio: 10.0805874 |  ineq vio: 0.1535856 |
Epoch 14 | Train loss: 0.1179916 |  Test mse: 0.0572751 |  opt gap: 0.0079633% |  eq vio: 5.0125923 |  ineq vio: 0.1410144 |
Epoch 15 | Train loss: 0.1106225 |  Test mse: 0.0597099 |  opt gap: 0.0100746% |  eq vio: 4.8036184 |  ineq vio: 0.4802924 |
Epoch 16 | Train loss: 0.1159822 |  Test mse: 0.0543581 |  opt gap: 0.0074207% |  eq vio: 5.2834558 |  ineq vio: 0.1991470 |
Epoch 17 | Train loss: 0.0987915 |  Test mse: 0.0553857 |  opt gap: 0.0118768% |  eq vio: 7.1069031 |  ineq vio: 0.0366233 |
Epoch 18 | Train loss: 0.1104939 |  Test mse: 0.0544974 |  opt gap: 0.0203512% |  eq vio: 6.1066322 |  ineq vio: 0.0169995 |
Epoch 19 | Train loss: 0.0962377 |  Test mse: 0.0526893 |  opt gap: 0.0103860% |  eq vio: 4.6081209 |  ineq vio: 0.4658683 |
Epoch 20 | Train loss: 0.1045622 |  Test mse: 0.0525362 |  opt gap: 0.0017352% |  eq vio: 8.1573524 |  ineq vio: 0.4317611 |
Epoch 21 | Train loss: 0.0927800 |  Test mse: 0.0503658 |  opt gap: 0.0108519% |  eq vio: 5.6109715 |  ineq vio: 0.3469505 |
Epoch 22 | Train loss: 0.0922372 |  Test mse: 0.0576446 |  opt gap: 0.0041814% |  eq vio: 5.2036877 |  ineq vio: 0.5197092 |
Epoch 23 | Train loss: 0.0875561 |  Test mse: 0.0511257 |  opt gap: -0.0015067% |  eq vio: 3.8083839 |  ineq vio: 0.0692179 |
Epoch 24 | Train loss: 0.0914119 |  Test mse: 0.0530096 |  opt gap: 0.0101288% |  eq vio: 3.8233223 |  ineq vio: 0.3130872 |
Epoch 25 | Train loss: 0.0875241 |  Test mse: 0.0524550 |  opt gap: 0.0023463% |  eq vio: 3.8752651 |  ineq vio: 0.0786257 |
Epoch 26 | Train loss: 0.0844796 |  Test mse: 0.0508226 |  opt gap: -0.0043581% |  eq vio: 4.7112236 |  ineq vio: 0.3682645 |
Epoch 27 | Train loss: 0.0853674 |  Test mse: 0.0486857 |  opt gap: 0.0067035% |  eq vio: 4.0979991 |  ineq vio: 0.3245791 |
Epoch 28 | Train loss: 0.0890130 |  Test mse: 0.0526090 |  opt gap: -0.0217484% |  eq vio: 5.1497836 |  ineq vio: 0.2688804 |
Epoch 29 | Train loss: 0.0810127 |  Test mse: 0.0511632 |  opt gap: -0.0048436% |  eq vio: 3.0762224 |  ineq vio: 0.2988772 |
Epoch 30 | Train loss: 0.0791530 |  Test mse: 0.0464417 |  opt gap: 0.0074377% |  eq vio: 5.2692652 |  ineq vio: 0.1055791 |
Epoch 31 | Train loss: 0.0767083 |  Test mse: 0.0487703 |  opt gap: 0.0057284% |  eq vio: 5.1492643 |  ineq vio: 0.0939550 |
Epoch 32 | Train loss: 0.0796113 |  Test mse: 0.0457009 |  opt gap: 0.0022099% |  eq vio: 4.8809853 |  ineq vio: 0.0714990 |
Epoch 33 | Train loss: 0.0743996 |  Test mse: 0.0470725 |  opt gap: -0.0049982% |  eq vio: 5.3525162 |  ineq vio: 0.0193614 |
Epoch 34 | Train loss: 0.0750122 |  Test mse: 0.0453370 |  opt gap: -0.0108869% |  eq vio: 9.1585827 |  ineq vio: 0.4227380 |
Epoch 35 | Train loss: 0.0743638 |  Test mse: 0.0466842 |  opt gap: 0.0060517% |  eq vio: 3.8614223 |  ineq vio: 0.3512167 |
Epoch 36 | Train loss: 0.0763882 |  Test mse: 0.0461277 |  opt gap: -0.0128720% |  eq vio: 3.1196933 |  ineq vio: 0.1834333 |
Epoch 37 | Train loss: 0.0691596 |  Test mse: 0.0445949 |  opt gap: 0.0109515% |  eq vio: 3.2941270 |  ineq vio: 0.1227979 |
Epoch 38 | Train loss: 0.0675130 |  Test mse: 0.0456669 |  opt gap: -0.0051383% |  eq vio: 2.3403103 |  ineq vio: 0.1130649 |
Epoch 39 | Train loss: 0.0669805 |  Test mse: 0.0403323 |  opt gap: -0.0107197% |  eq vio: 2.7676194 |  ineq vio: 0.0952660 |
Epoch 40 | Train loss: 0.0652887 |  Test mse: 0.0422678 |  opt gap: -0.0071717% |  eq vio: 3.7228715 |  ineq vio: 0.2439743 |
Epoch 41 | Train loss: 0.0669759 |  Test mse: 0.0428699 |  opt gap: 0.0131941% |  eq vio: 5.1262841 |  ineq vio: 0.0879190 |
Epoch 42 | Train loss: 0.0659273 |  Test mse: 0.0407325 |  opt gap: -0.0108446% |  eq vio: 3.9263191 |  ineq vio: 0.3522302 |
Epoch 43 | Train loss: 0.0652156 |  Test mse: 0.0397147 |  opt gap: 0.0106632% |  eq vio: 4.5279913 |  ineq vio: 0.2117487 |
Epoch 44 | Train loss: 0.0609913 |  Test mse: 0.0433121 |  opt gap: -0.0140023% |  eq vio: 3.4404736 |  ineq vio: 0.0266693 |
Epoch 45 | Train loss: 0.0616303 |  Test mse: 0.0328705 |  opt gap: -0.0046397% |  eq vio: 2.5027485 |  ineq vio: 0.1817501 |
Epoch 46 | Train loss: 0.0572853 |  Test mse: 0.0379109 |  opt gap: -0.0044859% |  eq vio: 3.5721264 |  ineq vio: 0.0207343 |
Epoch 47 | Train loss: 0.0575367 |  Test mse: 0.0371568 |  opt gap: 0.0016793% |  eq vio: 4.3678808 |  ineq vio: 0.6280721 |
Epoch 48 | Train loss: 0.0611676 |  Test mse: 0.0391230 |  opt gap: -0.0075577% |  eq vio: 3.9390316 |  ineq vio: 0.1304742 |
Epoch 49 | Train loss: 0.0595395 |  Test mse: 0.0371225 |  opt gap: 0.0024364% |  eq vio: 4.0577312 |  ineq vio: 0.2583650 |
Epoch 50 | Train loss: 0.0561018 |  Test mse: 0.0400082 |  opt gap: 0.0064530% |  eq vio: 4.7658043 |  ineq vio: 0.2669308 |

In [51]:
model_res = ResidualNeuralNetwork(x_size=len(inputs),
                                  y_size=len(outputs),
                                  width=64,
                                  depth=6).to(device)

a = model_train_test(train_data_loader, test_data_loader, model_res, nn.MSELoss(), opf_metric, epochs=50)

==============================================Start training on cuda===========================================
Epoch 1 | Train loss: 0.3726798 |  Test mse: 0.1459895 |  opt gap: 0.0123390% |  eq vio: 105.0272446 |  ineq vio: 32.4881058 |
Epoch 2 | Train loss: 0.1032014 |  Test mse: 0.0767267 |  opt gap: 0.0155402% |  eq vio: 113.4449005 |  ineq vio: 35.0181732 |
Epoch 3 | Train loss: 0.0601017 |  Test mse: 0.0673808 |  opt gap: -0.0088588% |  eq vio: 72.6319275 |  ineq vio: 16.2297115 |
Epoch 4 | Train loss: 0.0502787 |  Test mse: 0.0557695 |  opt gap: -0.0143666% |  eq vio: 76.9824677 |  ineq vio: 22.3549652 |
Epoch 5 | Train loss: 0.0414508 |  Test mse: 0.0533770 |  opt gap: 0.0030453% |  eq vio: 66.8304367 |  ineq vio: 17.8328362 |
Epoch 6 | Train loss: 0.0352313 |  Test mse: 0.0555628 |  opt gap: -0.0270800% |  eq vio: 63.6776505 |  ineq vio: 12.9448967 |
Epoch 7 | Train loss: 0.0319136 |  Test mse: 0.0469129 |  opt gap: -0.0036366% |  eq vio: 48.3069954 |  ineq vio: 8.7038841 |
Epoch 8 | Train loss: 0.0280017 |  Test mse: 0.0418679 |  opt gap: 0.0102704% |  eq vio: 37.8874435 |  ineq vio: 5.8224077 |
Epoch 9 | Train loss: 0.0266926 |  Test mse: 0.0385216 |  opt gap: -0.0025523% |  eq vio: 41.0981979 |  ineq vio: 9.1049137 |
Epoch 10 | Train loss: 0.0253224 |  Test mse: 0.0420601 |  opt gap: -0.0137113% |  eq vio: 35.4926376 |  ineq vio: 6.8302631 |
Epoch 11 | Train loss: 0.0239042 |  Test mse: 0.0389944 |  opt gap: -0.0019427% |  eq vio: 56.5871429 |  ineq vio: 9.4878426 |
Epoch 12 | Train loss: 0.0241378 |  Test mse: 0.0439433 |  opt gap: -0.0031742% |  eq vio: 44.8294067 |  ineq vio: 7.3588858 |
Epoch 13 | Train loss: 0.0233662 |  Test mse: 0.0416931 |  opt gap: -0.0257239% |  eq vio: 46.4835968 |  ineq vio: 7.3728175 |
Epoch 14 | Train loss: 0.0220293 |  Test mse: 0.0376328 |  opt gap: -0.0065504% |  eq vio: 35.3314095 |  ineq vio: 5.7894292 |
Epoch 15 | Train loss: 0.0212956 |  Test mse: 0.0346828 |  opt gap: 0.0087927% |  eq vio: 43.8036003 |  ineq vio: 6.2192202 |
Epoch 16 | Train loss: 0.0202403 |  Test mse: 0.0335735 |  opt gap: -0.0163722% |  eq vio: 43.4417610 |  ineq vio: 7.5423298 |
Epoch 17 | Train loss: 0.0194451 |  Test mse: 0.0478134 |  opt gap: 0.0334679% |  eq vio: 36.4161110 |  ineq vio: 4.4015608 |
Epoch 18 | Train loss: 0.0203978 |  Test mse: 0.0332594 |  opt gap: 0.0197384% |  eq vio: 41.7932205 |  ineq vio: 10.0550365 |
Epoch 19 | Train loss: 0.0184706 |  Test mse: 0.0288501 |  opt gap: 0.0102219% |  eq vio: 38.4814377 |  ineq vio: 5.1832199 |
Epoch 20 | Train loss: 0.0178195 |  Test mse: 0.0247745 |  opt gap: 0.0151470% |  eq vio: 50.8736191 |  ineq vio: 8.7241688 |
Epoch 21 | Train loss: 0.0180937 |  Test mse: 0.0284176 |  opt gap: 0.0019396% |  eq vio: 45.6751976 |  ineq vio: 9.0569229 |
Epoch 22 | Train loss: 0.0169229 |  Test mse: 0.0345791 |  opt gap: 0.0090068% |  eq vio: 30.7500839 |  ineq vio: 3.3308611 |
Epoch 23 | Train loss: 0.0167627 |  Test mse: 0.0306916 |  opt gap: 0.0001811% |  eq vio: 27.7105045 |  ineq vio: 2.9413643 |
Epoch 24 | Train loss: 0.0161482 |  Test mse: 0.0312619 |  opt gap: -0.0073884% |  eq vio: 34.5950165 |  ineq vio: 5.7073092 |
Epoch 25 | Train loss: 0.0162070 |  Test mse: 0.0269141 |  opt gap: -0.0013086% |  eq vio: 40.8021851 |  ineq vio: 5.2095418 |
Epoch 26 | Train loss: 0.0162479 |  Test mse: 0.0330696 |  opt gap: 0.0107720% |  eq vio: 30.8197365 |  ineq vio: 4.3909616 |
Epoch 27 | Train loss: 0.0157711 |  Test mse: 0.0472268 |  opt gap: -0.0149434% |  eq vio: 32.3818359 |  ineq vio: 6.5499907 |
Epoch 28 | Train loss: 0.0154020 |  Test mse: 0.0270103 |  opt gap: 0.0156228% |  eq vio: 33.2517700 |  ineq vio: 5.8997264 |
Epoch 29 | Train loss: 0.0137894 |  Test mse: 0.0285784 |  opt gap: 0.0255474% |  eq vio: 33.3584442 |  ineq vio: 4.7155457 |
Epoch 30 | Train loss: 0.0146993 |  Test mse: 0.0283040 |  opt gap: -0.0049938% |  eq vio: 26.8035049 |  ineq vio: 3.1180897 |
Epoch 31 | Train loss: 0.0144905 |  Test mse: 0.0213636 |  opt gap: 0.0094762% |  eq vio: 30.7588253 |  ineq vio: 5.5707502 |
Epoch 32 | Train loss: 0.0138417 |  Test mse: 0.0337274 |  opt gap: 0.0185465% |  eq vio: 27.6545048 |  ineq vio: 3.3516798 |
Epoch 33 | Train loss: 0.0134358 |  Test mse: 0.0243174 |  opt gap: -0.0203715% |  eq vio: 26.5037231 |  ineq vio: 4.2817326 |
Epoch 34 | Train loss: 0.0140296 |  Test mse: 0.0250628 |  opt gap: 0.0018963% |  eq vio: 28.3709068 |  ineq vio: 4.4900198 |
Epoch 35 | Train loss: 0.0145154 |  Test mse: 0.0390129 |  opt gap: 0.0032246% |  eq vio: 29.0850372 |  ineq vio: 4.2289281 |
Epoch 36 | Train loss: 0.0129503 |  Test mse: 0.0310712 |  opt gap: 0.0132907% |  eq vio: 32.1237030 |  ineq vio: 2.7522795 |
Epoch 37 | Train loss: 0.0144013 |  Test mse: 0.0259438 |  opt gap: 0.0206492% |  eq vio: 22.7277184 |  ineq vio: 3.2969046 |
Epoch 38 | Train loss: 0.0120307 |  Test mse: 0.0338445 |  opt gap: -0.0101018% |  eq vio: 22.8388863 |  ineq vio: 2.4356632 |
Epoch 39 | Train loss: 0.0112418 |  Test mse: 0.0305905 |  opt gap: 0.0197478% |  eq vio: 27.1132832 |  ineq vio: 4.1998129 |
Epoch 40 | Train loss: 0.0136021 |  Test mse: 0.0243508 |  opt gap: -0.0091430% |  eq vio: 30.2883167 |  ineq vio: 5.6411967 |
Epoch 41 | Train loss: 0.0121149 |  Test mse: 0.0261690 |  opt gap: -0.0138611% |  eq vio: 25.7691078 |  ineq vio: 3.7604060 |
Epoch 42 | Train loss: 0.0112049 |  Test mse: 0.0161337 |  opt gap: 0.0067371% |  eq vio: 20.5025215 |  ineq vio: 1.4671061 |
Epoch 43 | Train loss: 0.0121174 |  Test mse: 0.0230195 |  opt gap: 0.0111788% |  eq vio: 20.4125404 |  ineq vio: 1.6596324 |
Epoch 44 | Train loss: 0.0114451 |  Test mse: 0.0369668 |  opt gap: -0.0011553% |  eq vio: 24.0746422 |  ineq vio: 2.9700978 |
Epoch 45 | Train loss: 0.0120088 |  Test mse: 0.0210935 |  opt gap: 0.0036524% |  eq vio: 24.2994194 |  ineq vio: 1.1409730 |
Epoch 46 | Train loss: 0.0115884 |  Test mse: 0.0166583 |  opt gap: -0.0101727% |  eq vio: 21.3893394 |  ineq vio: 2.1407688 |
Epoch 47 | Train loss: 0.0124123 |  Test mse: 0.0395718 |  opt gap: 0.0035923% |  eq vio: 21.1758537 |  ineq vio: 3.0850682 |
Epoch 48 | Train loss: 0.0101087 |  Test mse: 0.0220648 |  opt gap: 0.0239830% |  eq vio: 20.8799438 |  ineq vio: 1.9028687 |
Epoch 49 | Train loss: 0.0097821 |  Test mse: 0.0242924 |  opt gap: 0.0100782% |  eq vio: 24.6534882 |  ineq vio: 2.6848507 |
Epoch 50 | Train loss: 0.0111329 |  Test mse: 0.0234742 |  opt gap: 0.0157483% |  eq vio: 20.9400826 |  ineq vio: 1.1341054 |

{'train_losses': [0.37267980828881264,
  0.10320139509439469,
  0.060101729184389115,
  0.05027872336655855,
  0.04145084691792727,
  0.035231254808604714,
  0.03191361517086625,
  0.02800167289376259,
  0.02669259575009346,
  0.02532236912474036,
  0.02390420011803508,
  0.024137804517522454,
  0.023366205386817454,
  0.022029305892065167,
  0.02129560793377459,
  0.020240311598405242,
  0.019445132953114806,
  0.020397845385596157,
  0.01847060682810843,
  0.017819520263932645,
  0.018093730382621288,
  0.016922882163897156,
  0.016762671461328864,
  0.016148173727095125,
  0.01620698005799204,
  0.016247864903882147,
  0.015771064506843686,
  0.015402019293047488,
  0.01378941469360143,
  0.014699292388744652,
  0.014490492088720202,
  0.013841680405661463,
  0.013435832071118058,
  0.014029553822241723,
  0.014515363225713371,
  0.012950294625945389,
  0.014401263574138283,
  0.012030673330649734,
  0.011241766932420433,
  0.013602074710652232,
  0.012114936096593738,
  0.011204910925589501,
  0.012117373397573829,
  0.011445052108727396,
  0.012008811098523437,
  0.011588419556617737,
  0.01241232156008482,
  0.010108660171739756,
  0.009782148135825992,
  0.01113290558103472],
 'test_mse': [tensor([[1.0870e-05, 8.1986e-03, 4.3390e-01, 1.4130e-01, 9.8797e-02, 1.2079e-02,
           3.3761e-03, 2.6681e-02, 5.9678e-04, 1.5883e-02, 2.6819e-05, 5.1286e-03,
           2.2016e-03, 3.0240e-03, 1.2052e-03, 1.8721e-04, 2.3810e-03, 5.5738e-03,
           3.6290e-03, 2.2757e-03],
          [1.2744e-05, 1.3137e-02, 5.9332e-02, 2.8073e-03, 7.5205e-02, 1.4647e-03,
           7.1219e-02, 2.4004e-02, 1.1004e-01, 7.0643e-02, 8.9943e-03, 2.7307e-03,
           1.4665e-04, 4.0258e-05, 3.0997e-03, 1.3362e-04, 5.4711e-04, 9.3740e-03,
           3.4904e-03, 2.0596e-05],
          [8.5820e-03, 2.8425e-01, 5.6124e+00, 2.8230e-01, 3.4991e+00, 6.4221e-04,
           2.8057e-01, 2.2474e+00, 3.6814e-01, 6.9014e-01, 2.8489e-02, 1.9828e-01,
           5.8602e-02, 1.4329e-01, 7.9987e-02, 4.7312e-04, 1.3070e-03, 3.8536e-03,
           6.7954e-04, 1.0253e-03],
          [1.0930e-02, 1.4640e-01, 1.0530e+00, 1.8042e-01, 8.4567e-01, 9.9090e-04,
           1.8864e-01, 4.5260e-01, 5.6182e-03, 5.7955e-01, 1.2156e-02, 4.4800e-02,
           2.9318e-02, 3.7356e-02, 1.2791e-02, 5.8199e-03, 2.5360e-05, 1.2087e-02,
           8.7059e-03, 2.0905e-04],
          [2.2530e-03, 6.6456e-01, 1.0260e-02, 5.9915e-01, 1.3088e-03, 3.5204e-03,
           4.0605e-05, 2.8677e-01, 1.9511e-01, 7.7846e-01, 1.2075e-02, 6.9716e-02,
           5.4223e-03, 1.5918e-04, 1.0980e-02, 5.3382e-04, 1.6862e-03, 1.6956e-02,
           7.4676e-03, 6.4772e-03],
          [3.9789e-04, 9.0758e-03, 1.6221e-04, 1.1931e+00, 6.2983e-01, 4.3606e-03,
           2.0454e-02, 3.5125e-01, 1.5609e-01, 1.3325e+00, 7.9389e-03, 8.0857e-02,
           8.2741e-03, 9.6907e-04, 1.5585e-02, 2.2836e-03, 2.7985e-05, 2.1477e-02,
           1.8271e-03, 1.1535e-02],
          [6.1551e-04, 1.0999e-02, 2.0023e-01, 1.5710e-01, 2.3989e-02, 1.9862e-03,
           1.5468e-01, 1.6267e-01, 4.7262e-01, 2.6697e-03, 1.5647e-06, 4.8770e-03,
           9.7197e-05, 6.6327e-06, 3.5455e-04, 1.0285e-04, 5.8225e-06, 6.5353e-03,
           6.5000e-03, 1.6279e-05],
          [8.1909e-03, 2.2688e-01, 2.5520e+00, 2.4086e-02, 1.1200e+00, 1.0269e-01,
           1.4627e+00, 6.3163e-02, 6.1147e-01, 1.1264e+00, 1.1200e-02, 9.3499e-02,
           1.4676e-02, 4.7412e-02, 4.0111e-02, 5.5676e-03, 4.2017e-05, 1.0618e-05,
           7.3669e-03, 2.4413e-03],
          [1.5629e-03, 8.0735e-03, 1.9811e-01, 2.5907e-02, 4.6610e-01, 1.9116e-02,
           3.6510e-02, 1.0694e-01, 3.2103e-01, 8.4787e-01, 7.2063e-05, 2.4775e-02,
           1.3474e-03, 2.0254e-02, 6.2361e-03, 2.3585e-04, 6.1589e-04, 1.2915e-02,
           3.8918e-03, 2.6996e-02],
          [4.8501e-03, 1.1116e-03, 2.9192e-01, 9.7859e-03, 1.6250e-01, 1.6972e-02,
           5.3948e-02, 8.3797e-02, 2.7326e-02, 1.6077e-01, 2.2735e-03, 3.0733e-02,
           2.1453e-03, 2.3431e-03, 1.7917e-05, 4.8403e-03, 4.5729e-03, 4.3547e-03,
           1.0998e-03, 6.4122e-03],
          [4.0847e-03, 5.7665e-06, 8.2912e-03, 1.0332e-01, 1.1937e-02, 8.3907e-03,
           3.0796e-02, 2.8802e-02, 2.0213e-01, 1.3011e-01, 4.4536e-04, 1.9186e-02,
           2.4975e-04, 6.7284e-03, 3.9415e-03, 6.0151e-07, 7.6764e-03, 5.5208e-03,
           1.8650e-04, 2.7637e-02],
          [2.3254e-03, 4.5717e-04, 4.8358e-01, 8.0638e-01, 1.8764e+00, 5.7283e-03,
           9.9356e-02, 1.2051e-01, 7.4662e-01, 1.6244e+00, 8.5330e-04, 3.6597e-02,
           2.2429e-03, 2.4924e-05, 2.5778e-02, 1.2817e-04, 3.3239e-06, 3.9084e-02,
           3.8839e-03, 6.6807e-03],
          [1.4663e-04, 1.5175e-02, 2.7347e-03, 2.7866e-01, 1.9800e-01, 1.6915e-06,
           3.3962e-04, 7.0048e-01, 2.1807e-01, 2.2584e-01, 3.2264e-03, 4.9038e-02,
           2.0937e-02, 2.2508e-03, 1.8028e-02, 1.7695e-04, 2.8579e-08, 1.3519e-03,
           6.1682e-05, 6.0760e-03],
          [2.3596e-03, 1.0640e-01, 4.0825e-02, 6.9437e-02, 5.2856e-03, 8.5068e-02,
           1.3720e+00, 1.5791e-01, 5.8568e-03, 3.1075e+00, 2.5088e-02, 3.8733e-03,
           4.6308e-03, 1.9144e-03, 1.9718e-03, 1.0391e-04, 3.8883e-04, 1.6069e-03,
           6.0339e-03, 8.9190e-04],
          [5.5496e-03, 8.0948e-04, 3.7697e-01, 2.5599e-01, 7.4279e-04, 3.4506e-03,
           8.0801e-03, 4.5996e-02, 2.3762e-03, 6.3655e-05, 3.3576e-06, 1.2442e-05,
           1.8835e-03, 1.9286e-02, 1.1258e-03, 1.8396e-02, 1.6469e-04, 6.7250e-03,
           9.3453e-03, 3.2754e-03],
          [6.5191e-04, 2.4556e-01, 4.9459e-03, 1.2065e+00, 1.5881e-01, 1.9977e-01,
           4.3925e+00, 1.1105e-01, 2.1738e-02, 8.8860e+00, 1.7447e-02, 7.1383e-02,
           2.2230e-02, 8.1630e-03, 1.2375e-02, 2.2781e-03, 1.5796e-03, 7.9835e-03,
           2.8940e-03, 5.9252e-03],
          [5.8868e-03, 6.1364e-03, 4.3713e-01, 1.1791e-01, 9.9537e-02, 1.4106e-03,
           7.4681e-04, 1.3223e-05, 3.3417e-01, 7.1345e-02, 1.1816e-02, 2.6091e-03,
           1.2661e-02, 2.2098e-03, 6.0896e-04, 5.1850e-04, 2.5748e-03, 2.0828e-04,
           8.2483e-03, 5.8753e-05],
          [8.5064e-03, 5.1279e-02, 2.5361e-03, 4.6184e-01, 1.0352e-01, 7.9174e-03,
           2.5524e-02, 9.2548e-02, 6.5307e-04, 3.2315e-01, 8.1011e-03, 6.2772e-02,
           2.1638e-03, 5.1373e-04, 5.9973e-03, 2.5370e-03, 2.0557e-05, 1.8509e-02,
           1.6895e-03, 6.4929e-03],
          [6.6949e-04, 9.5646e-02, 1.5719e-03, 8.5140e-02, 7.9324e-03, 4.6836e-03,
           3.6274e-01, 7.4600e-02, 3.1253e-01, 8.3384e-02, 3.2073e-06, 1.2698e-03,
           8.6571e-04, 2.8007e-05, 1.4408e-05, 2.9537e-04, 1.4007e-03, 6.6992e-04,
           2.0351e-03, 1.2678e-04],
          [4.4641e-04, 3.5891e-03, 4.0536e-01, 3.6553e-01, 2.6647e-02, 3.2575e-03,
           1.5958e-03, 3.0865e-02, 7.6160e-02, 3.0251e-02, 4.8476e-03, 4.2603e-04,
           2.0185e-03, 1.5065e-03, 7.1633e-05, 5.1489e-07, 1.8750e-03, 2.5214e-03,
           3.7109e-03, 6.4099e-05],
          [2.2338e-03, 8.2818e-04, 5.0194e-01, 2.6209e-03, 3.2125e-01, 3.3182e-02,
           1.0160e+00, 2.8311e-03, 2.7928e-02, 1.0751e+00, 5.7472e-03, 1.7580e-02,
           2.9489e-02, 1.3820e-02, 8.1438e-03, 1.2867e-04, 9.7209e-03, 4.9182e-03,
           3.7232e-03, 4.5585e-04],
          [2.8885e-04, 4.5101e-02, 1.0018e-03, 1.1864e-01, 6.4068e-02, 6.3076e-03,
           1.1478e-02, 9.6667e-03, 9.9723e-02, 2.1806e-03, 1.3924e-03, 2.2939e-02,
           4.4333e-03, 7.0387e-04, 2.8415e-03, 9.8892e-04, 9.6632e-05, 2.6702e-03,
           2.3690e-03, 7.6857e-04],
          [1.9850e-03, 1.1249e-01, 1.9383e-01, 7.0334e-02, 1.3175e-01, 6.4355e-02,
           8.0080e-01, 1.4527e-01, 3.4507e-01, 4.3365e-02, 8.1930e-04, 1.0742e-02,
           3.8833e-03, 5.0727e-03, 1.3057e-03, 2.1006e-03, 2.4858e-05, 3.3042e-05,
           2.8820e-03, 3.2282e-03],
          [7.3785e-04, 1.7495e-01, 3.5994e-02, 4.5837e-02, 9.3301e-02, 4.8941e-02,
           8.2253e-01, 2.1546e-02, 7.6614e-01, 1.6314e-01, 1.3785e-03, 4.3852e-03,
           1.1897e-02, 1.3278e-03, 2.4332e-03, 1.8162e-03, 2.0346e-04, 3.9017e-06,
           4.1972e-04, 4.8623e-04],
          [1.0404e-03, 2.1417e-02, 9.8587e-02, 7.8778e-01, 4.8040e-02, 2.0109e-03,
           1.8012e-02, 2.9713e-01, 1.8741e-01, 5.0628e-03, 4.4306e-04, 9.6865e-03,
           6.2487e-03, 2.8314e-02, 1.5908e-03, 6.0730e-04, 4.2304e-03, 9.3635e-03,
           3.2601e-03, 3.8784e-03],
          [1.2995e-02, 4.4935e-02, 4.4083e-02, 5.6823e-01, 3.3541e-01, 2.1845e-03,
           5.2021e-03, 2.6397e-01, 1.6457e-02, 8.9952e-02, 2.3972e-03, 9.6907e-03,
           3.7282e-03, 6.7149e-02, 6.2374e-04, 8.7785e-04, 1.5496e-04, 8.0967e-03,
           4.8508e-04, 1.6468e-03],
          [8.3345e-08, 3.9055e-02, 3.8201e-02, 6.5799e-01, 4.7260e-02, 1.3627e-02,
           1.4455e-02, 1.2232e-01, 4.5219e-01, 3.8215e-02, 4.7409e-03, 1.8264e-02,
           2.0661e-02, 4.3207e-03, 7.1839e-03, 2.6122e-03, 2.7635e-03, 4.6840e-04,
           7.9115e-03, 8.0971e-04],
          [8.7953e-04, 6.2048e-03, 2.0648e+00, 4.1611e-02, 1.1301e+00, 1.5332e-03,
           1.4249e-01, 1.4190e-03, 1.0950e-02, 7.5021e-03, 2.4516e-02, 1.9738e-03,
           2.6861e-02, 2.3415e-02, 4.7834e-03, 2.8757e-03, 5.9137e-05, 2.7043e-02,
           6.8408e-03, 3.6785e-04],
          [1.4275e-03, 6.8244e-03, 1.0431e-03, 3.1234e-01, 1.2913e-01, 5.5854e-03,
           6.3224e-02, 2.0482e-01, 1.1992e-01, 5.2916e-01, 3.2749e-05, 6.9653e-03,
           6.8143e-03, 1.5944e-02, 4.2693e-03, 4.0389e-04, 5.2868e-04, 4.1556e-03,
           4.0773e-03, 4.8696e-04],
          [2.7315e-02, 2.9824e-02, 2.2694e-01, 1.7800e-01, 2.7074e-01, 1.5766e-03,
           3.3381e-02, 2.5517e-01, 4.4033e-01, 8.7904e-03, 1.5227e-02, 2.7170e-02,
           2.4653e-02, 5.5428e-02, 8.8567e-03, 6.6970e-03, 1.6330e-02, 3.8446e-03,
           4.8942e-04, 2.5394e-03],
          [2.2784e-04, 5.8027e-03, 1.0143e-01, 3.9139e-01, 8.5636e-01, 2.0993e-03,
           7.0890e-02, 5.1705e-02, 4.2043e-01, 1.1209e+00, 2.3992e-03, 8.7009e-03,
           1.0222e-03, 2.6689e-03, 2.8985e-04, 1.1201e-03, 7.1964e-03, 1.0856e-02,
           4.5585e-03, 2.1807e-03],
          [1.3460e-03, 1.0847e-01, 1.5269e-01, 8.6902e-02, 1.7377e-01, 8.8766e-04,
           2.1468e-01, 2.0220e-02, 1.2523e-01, 1.8163e-01, 4.8642e-03, 2.2618e-02,
           1.0370e-02, 4.4538e-03, 7.5450e-03, 1.6375e-04, 1.2122e-02, 1.1346e-05,
           3.2831e-03, 3.4483e-05]], device='cuda:0'),
  tensor([[2.4854e-03, 1.6771e-03, 2.0196e-01, 2.4184e-01, 1.5018e-02, 5.4814e-03,
           1.0836e-04, 7.7142e-02, 1.9520e-02, 1.1740e-02, 1.9891e-03, 1.4608e-03,
           9.0423e-05, 3.8745e-03, 1.2065e-05, 1.3052e-03, 3.4704e-03, 1.9582e-03,
           1.5445e-03, 2.4910e-03],
          [1.5156e-04, 1.0838e-03, 4.7774e-03, 2.3718e-02, 2.9120e-04, 1.2445e-03,
           2.6328e-02, 1.3271e-02, 4.3080e-02, 1.6512e-01, 1.5691e-06, 2.9052e-03,
           3.2233e-03, 2.1012e-05, 1.6073e-04, 1.9517e-03, 9.2712e-03, 1.1045e-03,
           8.4635e-04, 6.2694e-05],
          [1.6083e-03, 4.3139e-02, 1.2192e+00, 2.7695e-01, 7.9630e-02, 1.0534e-02,
           5.4947e-03, 5.6023e-01, 2.8969e-01, 1.7449e-01, 2.5560e-02, 7.5160e-05,
           4.6273e-03, 7.5680e-03, 6.6866e-05, 2.5960e-03, 4.7876e-02, 5.4999e-06,
           6.3869e-04, 8.9731e-03],
          [1.7610e-03, 1.0796e-02, 2.2063e-02, 2.2178e-02, 5.4979e-04, 2.4414e-03,
           7.8877e-02, 6.1102e-02, 6.6029e-03, 4.6898e-02, 4.3723e-03, 2.6631e-04,
           1.1112e-03, 5.3261e-03, 1.3982e-03, 8.1637e-03, 1.8538e-02, 8.1398e-04,
           3.3568e-05, 7.7742e-05],
          [9.3456e-05, 4.8788e-01, 2.6170e-01, 1.6477e-01, 3.5873e-01, 8.6869e-06,
           5.8060e-03, 5.2435e-02, 1.4637e-01, 7.2250e-03, 5.3566e-03, 2.8067e-02,
           1.7876e-03, 5.2791e-03, 4.0921e-03, 2.8228e-03, 2.3648e-03, 1.6727e-03,
           3.7347e-03, 3.9449e-03],
          [1.1536e-06, 4.3061e-03, 5.6941e-01, 3.6047e-01, 1.5775e-06, 7.6073e-04,
           9.6011e-05, 4.9090e-02, 1.3983e-01, 1.3279e-01, 1.3038e-02, 2.4349e-02,
           4.4825e-03, 2.8685e-03, 5.2989e-03, 7.0431e-03, 1.5224e-05, 1.9152e-03,
           5.8154e-03, 7.5486e-03],
          [1.4085e-04, 7.4562e-06, 1.7514e-01, 1.6210e-01, 2.9381e-03, 1.8114e-03,
           7.1197e-02, 1.2244e-01, 3.6532e-01, 7.4406e-02, 5.2606e-03, 7.1858e-03,
           1.3669e-03, 7.8219e-04, 3.1490e-06, 2.8827e-03, 7.6175e-03, 2.0992e-04,
           7.2095e-04, 2.6903e-04],
          [4.8190e-03, 9.0623e-02, 7.5026e-01, 5.8162e-02, 1.1954e-01, 1.0747e-01,
           1.3191e+00, 1.0590e-02, 3.8793e-01, 1.4012e+00, 2.4265e-06, 7.7191e-03,
           1.6194e-04, 2.4568e-03, 3.8641e-03, 3.4178e-04, 2.5471e-04, 9.8136e-04,
           5.6156e-04, 2.1322e-04],
          [4.9570e-03, 3.4131e-02, 1.2036e-03, 1.2419e-02, 6.6705e-02, 1.1686e-04,
           4.1396e-03, 1.0826e-02, 2.0771e-01, 4.1624e-02, 7.0050e-03, 1.2391e-02,
           2.9569e-05, 7.0824e-03, 4.1947e-03, 1.8967e-03, 7.0564e-03, 2.2231e-03,
           1.3025e-03, 1.5959e-02],
          [2.0350e-03, 2.8113e-03, 4.6355e-02, 6.0888e-02, 1.4200e-02, 1.0666e-03,
           1.1026e-02, 2.3115e-02, 5.1316e-02, 2.2912e-02, 6.4170e-03, 1.0186e-02,
           2.1874e-04, 1.1822e-03, 1.0342e-03, 2.9914e-04, 3.0500e-03, 3.3837e-03,
           3.7776e-03, 1.1859e-02],
          [2.4752e-03, 3.2492e-03, 2.1824e-05, 2.1168e-02, 9.7427e-03, 1.3570e-03,
           1.9762e-02, 1.0758e-02, 2.6147e-01, 2.3304e-02, 6.4761e-03, 2.4081e-02,
           9.7816e-05, 1.4323e-03, 6.5426e-03, 3.9237e-04, 2.8405e-03, 1.0380e-04,
           2.5335e-06, 1.2340e-02],
          [5.2513e-04, 1.2078e-02, 2.9601e-02, 3.1761e-01, 6.6119e-01, 7.5044e-04,
           1.8320e-02, 8.2307e-03, 4.6066e-01, 3.0908e-01, 8.2082e-03, 2.3611e-02,
           6.7147e-04, 2.7379e-03, 1.4287e-02, 5.1542e-03, 5.7933e-03, 1.0342e-02,
           1.1318e-05, 3.2111e-03],
          [7.9756e-04, 3.8932e-04, 2.0339e-01, 4.1353e-02, 6.8494e-03, 6.1291e-04,
           1.5235e-04, 2.8151e-01, 2.9564e-01, 7.8542e-03, 3.3587e-03, 3.1232e-02,
           5.3203e-04, 1.3919e-03, 7.9488e-04, 9.0953e-03, 3.7660e-03, 5.7089e-04,
           1.0662e-02, 1.4019e-03],
          [1.0120e-03, 1.2938e-01, 2.5969e-02, 2.3509e-03, 1.4184e-01, 8.2434e-02,
           1.4789e+00, 5.4146e-02, 1.7880e-04, 1.9943e+00, 3.6155e-04, 7.6117e-04,
           3.4842e-03, 2.2731e-04, 9.3574e-05, 1.4229e-03, 3.7645e-03, 1.9315e-04,
           1.2834e-03, 9.2483e-04],
          [2.9116e-05, 1.1868e-02, 6.2682e-01, 2.4171e-01, 3.7150e-02, 3.2304e-03,
           2.4768e-05, 5.5366e-03, 3.7205e-02, 1.3133e-03, 2.0168e-04, 7.4469e-07,
           2.9851e-03, 7.9745e-03, 7.3006e-05, 3.3554e-03, 2.3833e-04, 1.2317e-04,
           2.2826e-03, 5.3787e-03],
          [3.3447e-05, 2.1113e-01, 5.1156e-01, 3.7376e-01, 2.0352e-01, 1.8795e-01,
           4.3302e+00, 3.4782e-04, 1.1815e-05, 5.4667e+00, 4.4454e-03, 3.0712e-03,
           5.2483e-04, 3.0443e-04, 2.3765e-04, 5.2279e-03, 5.5085e-04, 5.5574e-04,
           7.1594e-04, 3.7667e-03],
          [2.0132e-03, 3.1608e-02, 3.4309e-01, 8.3445e-02, 9.7115e-02, 7.5496e-03,
           4.9958e-04, 7.8521e-03, 7.4182e-02, 7.7929e-03, 1.5357e-03, 3.9603e-03,
           3.7117e-03, 4.6653e-05, 1.2119e-03, 2.0631e-04, 1.7637e-03, 1.1061e-02,
           3.8071e-03, 3.0278e-03],
          [1.3545e-03, 2.1313e-02, 2.7465e-01, 1.4904e-01, 2.8441e-02, 1.5602e-03,
           4.1295e-03, 3.0407e-02, 5.9063e-03, 2.0687e-02, 6.1594e-03, 1.7504e-02,
           2.2838e-03, 3.7669e-04, 4.6117e-03, 1.2958e-03, 2.2169e-04, 3.5584e-04,
           6.2069e-03, 5.6546e-03],
          [3.5477e-06, 3.1319e-02, 4.4801e-04, 9.1673e-02, 2.7742e-06, 3.9422e-03,
           2.4744e-01, 6.0626e-02, 2.3367e-01, 1.4492e-01, 3.5773e-03, 6.4545e-03,
           6.2375e-04, 1.3052e-03, 3.4706e-05, 3.8541e-04, 7.9345e-03, 4.4858e-04,
           1.6035e-03, 1.8058e-06],
          [7.5371e-04, 1.7855e-02, 4.5574e-01, 2.1660e-01, 9.0018e-02, 9.7988e-03,
           7.0720e-05, 9.0154e-03, 6.2768e-03, 9.1193e-06, 2.2514e-03, 1.6485e-03,
           4.4789e-03, 1.7583e-03, 1.1882e-03, 1.1341e-03, 4.4191e-03, 2.3389e-03,
           9.0846e-04, 2.5424e-03],
          [3.9672e-05, 2.7658e-03, 2.4071e-02, 1.4531e-01, 3.5569e-04, 1.2638e-02,
           7.4070e-01, 9.4647e-03, 1.8241e-04, 2.5800e-01, 9.8293e-03, 4.2105e-03,
           1.4102e-03, 1.2645e-03, 6.7636e-03, 8.9995e-03, 2.9016e-03, 9.8007e-03,
           1.3416e-03, 1.2424e-03],
          [9.1488e-05, 1.1187e-02, 6.8588e-02, 2.4139e-02, 7.5453e-03, 3.5736e-03,
           2.0368e-04, 3.0976e-04, 1.0739e-02, 8.2760e-02, 2.6904e-03, 2.5860e-03,
           1.1951e-03, 1.3238e-04, 8.0950e-06, 3.8685e-04, 1.6588e-04, 5.7805e-03,
           4.5978e-03, 1.6717e-03],
          [2.8494e-08, 9.9426e-02, 8.5002e-03, 3.3476e-01, 5.8396e-03, 7.5677e-02,
           1.0370e+00, 7.0213e-02, 3.9209e-01, 8.1363e-01, 2.5714e-02, 1.0393e-03,
           9.5286e-05, 2.6024e-03, 2.8053e-06, 4.0644e-03, 2.1397e-03, 1.1810e-02,
           6.1379e-05, 1.2267e-04],
          [1.6564e-06, 1.4639e-01, 2.7150e-02, 2.5019e-01, 1.3397e-02, 5.2588e-02,
           9.5912e-01, 9.0598e-02, 7.0037e-01, 7.9577e-01, 1.3912e-02, 2.1900e-03,
           6.6403e-05, 4.7418e-03, 1.6924e-04, 2.2155e-03, 3.8331e-03, 4.0106e-03,
           7.7447e-04, 2.1849e-04],
          [4.2481e-03, 1.7297e-03, 4.2398e-01, 3.2608e-01, 5.0570e-02, 4.8252e-03,
           1.3228e-05, 1.1500e-01, 2.2572e-01, 4.7390e-02, 1.6176e-04, 2.7957e-03,
           7.3518e-06, 1.0635e-02, 9.9237e-04, 2.8213e-03, 1.0230e-02, 4.4247e-04,
           6.2155e-04, 8.6564e-03],
          [6.1100e-03, 3.6796e-03, 5.7801e-03, 1.7147e-01, 1.4670e-02, 4.6589e-03,
           1.6497e-03, 5.5970e-02, 8.2469e-04, 3.2029e-03, 7.5811e-06, 4.3218e-03,
           2.4219e-03, 1.5644e-02, 2.0519e-03, 4.1587e-03, 1.3140e-02, 9.7140e-05,
           6.6823e-04, 7.0009e-03],
          [1.9080e-03, 3.7098e-02, 2.3167e-01, 2.4119e-01, 2.2418e-02, 6.5849e-03,
           3.4122e-03, 6.6495e-02, 1.0276e-01, 4.6246e-03, 4.6879e-03, 8.1967e-05,
           3.4304e-05, 5.9194e-04, 8.8300e-05, 1.3517e-05, 1.6925e-03, 1.7859e-02,
           6.1781e-03, 2.1152e-03],
          [2.0846e-03, 3.0183e-02, 2.9107e-01, 2.5096e-01, 4.2172e-02, 1.6803e-02,
           7.2629e-03, 1.6856e-01, 7.5668e-04, 6.1378e-01, 1.1339e-02, 2.5426e-02,
           1.8287e-03, 1.3393e-02, 7.4920e-03, 2.2241e-02, 5.8591e-04, 1.9150e-02,
           3.3839e-04, 4.3795e-04],
          [2.5540e-05, 9.4314e-03, 9.1601e-02, 4.5910e-02, 9.3206e-03, 7.7319e-03,
           1.7291e-02, 1.7987e-02, 3.7669e-02, 1.0755e-01, 8.3919e-04, 1.4889e-03,
           1.1365e-04, 7.2532e-05, 1.1052e-06, 3.5261e-03, 6.1447e-03, 2.5641e-03,
           3.7958e-03, 5.4047e-04],
          [1.4003e-02, 1.3015e-02, 6.6193e-03, 2.6035e-02, 1.7603e-02, 1.0370e-05,
           4.2854e-04, 1.2428e-01, 1.0032e-01, 1.4337e-02, 8.2739e-04, 1.0868e-02,
           7.1019e-03, 2.5792e-02, 2.7097e-03, 2.5649e-04, 1.2141e-02, 2.5949e-03,
           1.1973e-03, 6.2561e-04],
          [9.0310e-04, 6.2210e-03, 9.8038e-04, 1.5607e-01, 3.3475e-01, 9.0087e-04,
           2.9359e-02, 9.7627e-03, 3.0560e-01, 2.6060e-01, 9.9051e-03, 4.3285e-03,
           7.4543e-06, 1.8976e-03, 1.2130e-03, 9.8926e-05, 1.4627e-03, 1.5808e-03,
           7.4796e-04, 2.7543e-03],
          [7.9402e-06, 5.6965e-02, 2.2298e-02, 1.5697e-01, 1.7413e-02, 5.9536e-05,
           1.3567e-01, 3.1171e-03, 6.5126e-02, 3.2406e-01, 1.2078e-04, 1.2861e-02,
           1.8749e-04, 1.3536e-04, 4.1563e-03, 5.6194e-04, 1.5693e-02, 3.5972e-03,
           1.8467e-03, 1.2754e-04]], device='cuda:0'),
  tensor([[3.6625e-03, 3.5919e-03, 3.8301e-01, 9.7089e-02, 6.0304e-02, 6.2890e-03,
           3.3472e-04, 2.4770e-02, 5.1327e-03, 1.0560e-03, 6.2083e-05, 6.0925e-05,
           1.3522e-03, 7.7925e-03, 4.0453e-04, 1.1143e-03, 5.2341e-05, 1.7463e-03,
           4.9047e-03, 5.1235e-03],
          [5.1746e-06, 3.6157e-03, 2.8800e-02, 5.8264e-03, 1.2448e-02, 4.2951e-03,
           9.6946e-03, 1.3797e-02, 5.5746e-02, 7.4997e-03, 1.0031e-03, 7.8385e-05,

# Model CNN

In [52]:
class ConvolutionNetwork(nn.Module):
    def __init__(self, x_size, y_size, num_filter=32, kernel_size=3, depth=3):
        super().__init__()
        self.conv_layers = nn.ModuleList()

        self.conv_layers.append(nn.Conv1d(in_channels=1, out_channels=num_filter,kernel_size=kernel_size, padding=1))
        for _ in range(depth):
            self.conv_layers.append(nn.Conv1d(in_channels=num_filter, out_channels=num_filter, kernel_size=kernel_size, padding=1))

        self.fc1 = nn.Linear(num_filter * x_size, 128)
        self.fc2 = nn.Linear(128, y_size)

    def forward(self, x):
        x = x.unsqueeze(1)
        for conv in self.conv_layers:
            x = torch.nn.functional.relu(conv(x))

        x = x.view(x.size(0), -1)
        x = torch.nn.functional.relu(self.fc1(x))
        x = self.fc2(x)
        return x

In [53]:
model_cnn = ConvolutionNetwork(x_size=len(inputs),
                              y_size=len(outputs),
                              num_filter=64,
                              kernel_size=3,
                              depth=2).to(device)

In [63]:
results_2 = model_train_test(train_data_loader, test_data_loader, model_cnn, MSEPenaltyLoss(opf_metric),opf_metric, epochs=100, penalty=True)

==============================================Start training on cuda===========================================
Epoch 1 | Train loss: 0.0469010 |  Test mse: 0.0260672 |  opt gap: -0.0134344% |  eq vio: 2.3747652 |  ineq vio: 0.1468426 |
Epoch 2 | Train loss: 0.0340239 |  Test mse: 0.0205036 |  opt gap: -0.0089318% |  eq vio: 2.8188467 |  ineq vio: 0.0532132 |
Epoch 3 | Train loss: 0.0353772 |  Test mse: 0.0194423 |  opt gap: 0.0145895% |  eq vio: 2.5199761 |  ineq vio: 0.0910564 |
Epoch 4 | Train loss: 0.0295974 |  Test mse: 0.0235440 |  opt gap: -0.0028397% |  eq vio: 3.7911451 |  ineq vio: 0.1169322 |
Epoch 5 | Train loss: 0.0296833 |  Test mse: 0.0274494 |  opt gap: -0.0233585% |  eq vio: 2.4001877 |  ineq vio: 0.0990151 |
Epoch 6 | Train loss: 0.0296253 |  Test mse: 0.0167946 |  opt gap: 0.0045387% |  eq vio: 1.9588389 |  ineq vio: 0.1640822 |
Epoch 7 | Train loss: 0.0285837 |  Test mse: 0.0229337 |  opt gap: -0.0182824% |  eq vio: 2.2597280 |  ineq vio: 0.0806585 |
Epoch 8 | Train loss: 0.0284604 |  Test mse: 0.0197108 |  opt gap: 0.0095515% |  eq vio: 2.4268637 |  ineq vio: 0.1080119 |
Epoch 9 | Train loss: 0.0275032 |  Test mse: 0.0203635 |  opt gap: -0.0106571% |  eq vio: 1.3317167 |  ineq vio: 0.1145433 |
Epoch 10 | Train loss: 0.0276770 |  Test mse: 0.0232500 |  opt gap: -0.0174839% |  eq vio: 1.1363320 |  ineq vio: 0.0866242 |
Epoch 11 | Train loss: 0.0257198 |  Test mse: 0.0222850 |  opt gap: 0.0217194% |  eq vio: 1.9131181 |  ineq vio: 0.0861658 |
Epoch 12 | Train loss: 0.0303897 |  Test mse: 0.0316055 |  opt gap: -0.0152127% |  eq vio: 2.3450341 |  ineq vio: 0.1644110 |
Epoch 13 | Train loss: 0.0266338 |  Test mse: 0.0199653 |  opt gap: 0.0010964% |  eq vio: 2.1771030 |  ineq vio: 0.1613311 |
Epoch 14 | Train loss: 0.0257861 |  Test mse: 0.0200246 |  opt gap: 0.0008466% |  eq vio: 1.8672581 |  ineq vio: 0.0452486 |
Epoch 15 | Train loss: 0.0259995 |  Test mse: 0.0269375 |  opt gap: -0.0106092% |  eq vio: 1.7030380 |  ineq vio: 0.1847275 |
Epoch 16 | Train loss: 0.0230932 |  Test mse: 0.0163381 |  opt gap: 0.0055545% |  eq vio: 1.5597286 |  ineq vio: 0.0694104 |
Epoch 17 | Train loss: 0.0271173 |  Test mse: 0.0118302 |  opt gap: 0.0182101% |  eq vio: 1.9120884 |  ineq vio: 0.0637854 |
Epoch 18 | Train loss: 0.0231411 |  Test mse: 0.0141000 |  opt gap: 0.0017161% |  eq vio: 2.1743469 |  ineq vio: 0.2072391 |
Epoch 19 | Train loss: 0.0262635 |  Test mse: 0.0167644 |  opt gap: -0.0109069% |  eq vio: 1.7704406 |  ineq vio: 0.0595822 |
Epoch 20 | Train loss: 0.0256200 |  Test mse: 0.0243921 |  opt gap: 0.0224059% |  eq vio: 2.1525674 |  ineq vio: 0.0666448 |
Epoch 21 | Train loss: 0.0259236 |  Test mse: 0.0146347 |  opt gap: 0.0162091% |  eq vio: 2.0378761 |  ineq vio: 0.0674796 |
Epoch 22 | Train loss: 0.0256081 |  Test mse: 0.0157669 |  opt gap: -0.0033308% |  eq vio: 1.7800616 |  ineq vio: 0.0932883 |
Epoch 23 | Train loss: 0.0240668 |  Test mse: 0.0224184 |  opt gap: 0.0207936% |  eq vio: 1.6834922 |  ineq vio: 0.0216954 |
Epoch 24 | Train loss: 0.0252849 |  Test mse: 0.0207983 |  opt gap: -0.0030182% |  eq vio: 2.4878912 |  ineq vio: 0.0474568 |
Epoch 25 | Train loss: 0.0250709 |  Test mse: 0.0213501 |  opt gap: 0.0064346% |  eq vio: 1.7864347 |  ineq vio: 0.0194594 |
Epoch 26 | Train loss: 0.0269174 |  Test mse: 0.0253133 |  opt gap: -0.0169605% |  eq vio: 1.1528959 |  ineq vio: 0.0872834 |
Epoch 27 | Train loss: 0.0233151 |  Test mse: 0.0172080 |  opt gap: -0.0162265% |  eq vio: 2.5119145 |  ineq vio: 0.0432146 |
Epoch 28 | Train loss: 0.0226354 |  Test mse: 0.0180799 |  opt gap: -0.0140007% |  eq vio: 1.4488703 |  ineq vio: 0.0533465 |
Epoch 29 | Train loss: 0.0245817 |  Test mse: 0.0150086 |  opt gap: 0.0000761% |  eq vio: 1.9227438 |  ineq vio: 0.0310420 |
Epoch 30 | Train loss: 0.0226313 |  Test mse: 0.0154670 |  opt gap: -0.0128961% |  eq vio: 1.2906097 |  ineq vio: 0.0531487 |
Epoch 31 | Train loss: 0.0220062 |  Test mse: 0.0182973 |  opt gap: 0.0098880% |  eq vio: 2.3552642 |  ineq vio: 0.0462000 |
Epoch 32 | Train loss: 0.0242460 |  Test mse: 0.0124568 |  opt gap: 0.0059212% |  eq vio: 1.5383149 |  ineq vio: 0.0561244 |
Epoch 33 | Train loss: 0.0224503 |  Test mse: 0.0125697 |  opt gap: -0.0026144% |  eq vio: 1.0389715 |  ineq vio: 0.0571323 |
Epoch 34 | Train loss: 0.0229085 |  Test mse: 0.0162630 |  opt gap: 0.0040539% |  eq vio: 1.1125418 |  ineq vio: 0.0763028 |
Epoch 35 | Train loss: 0.0240515 |  Test mse: 0.0183348 |  opt gap: 0.0014478% |  eq vio: 1.9730877 |  ineq vio: 0.0524149 |
Epoch 36 | Train loss: 0.0223682 |  Test mse: 0.0199002 |  opt gap: -0.0155707% |  eq vio: 2.1029465 |  ineq vio: 0.1216919 |
Epoch 37 | Train loss: 0.0212468 |  Test mse: 0.0160749 |  opt gap: 0.0163969% |  eq vio: 1.2343000 |  ineq vio: 0.0264599 |
Epoch 38 | Train loss: 0.0212415 |  Test mse: 0.0178818 |  opt gap: -0.0091468% |  eq vio: 1.0539958 |  ineq vio: 0.0405692 |
Epoch 39 | Train loss: 0.0218631 |  Test mse: 0.0199831 |  opt gap: 0.0087563% |  eq vio: 1.8073593 |  ineq vio: 0.0244124 |
Epoch 40 | Train loss: 0.0221155 |  Test mse: 0.0159124 |  opt gap: 0.0017837% |  eq vio: 1.0107487 |  ineq vio: 0.0453579 |
Epoch 41 | Train loss: 0.0220869 |  Test mse: 0.0336881 |  opt gap: 0.0162079% |  eq vio: 1.7299631 |  ineq vio: 0.0246280 |
Epoch 42 | Train loss: 0.0211216 |  Test mse: 0.0119711 |  opt gap: -0.0089805% |  eq vio: 1.2181135 |  ineq vio: 0.1165701 |
Epoch 43 | Train loss: 0.0217502 |  Test mse: 0.0135157 |  opt gap: 0.0074378% |  eq vio: 1.2711203 |  ineq vio: 0.0333112 |
Epoch 44 | Train loss: 0.0224804 |  Test mse: 0.0116973 |  opt gap: -0.0012381% |  eq vio: 1.3086388 |  ineq vio: 0.0859927 |
Epoch 45 | Train loss: 0.0207766 |  Test mse: 0.0125534 |  opt gap: -0.0060686% |  eq vio: 2.0262008 |  ineq vio: 0.0210928 |
Epoch 46 | Train loss: 0.0213205 |  Test mse: 0.0143259 |  opt gap: -0.0042789% |  eq vio: 1.3451626 |  ineq vio: 0.0788462 |
Epoch 47 | Train loss: 0.0207442 |  Test mse: 0.0243219 |  opt gap: -0.0096845% |  eq vio: 1.6720476 |  ineq vio: 0.0782129 |
Epoch 48 | Train loss: 0.0214858 |  Test mse: 0.0130429 |  opt gap: 0.0016846% |  eq vio: 1.4450933 |  ineq vio: 0.0382029 |

KeyboardInterrupt:

In [55]:
results_3 = model_train_test(train_data_loader, test_data_loader, model_cnn, nn.MSELoss(),opf_metric, epochs=50, penalty=False)

==============================================Start training on cuda===========================================
Epoch 1 | Train loss: 0.0175382 |  Test mse: 0.0387685 |  opt gap: -0.0299839% |  eq vio: 3.2078347 |  ineq vio: 0.4683458 |
Epoch 2 | Train loss: 0.0150754 |  Test mse: 0.0338906 |  opt gap: -0.0107389% |  eq vio: 2.9027910 |  ineq vio: 0.2604286 |
Epoch 3 | Train loss: 0.0153919 |  Test mse: 0.0371200 |  opt gap: 0.0075507% |  eq vio: 3.3280730 |  ineq vio: 0.2333445 |
Epoch 4 | Train loss: 0.0128469 |  Test mse: 0.0247826 |  opt gap: 0.0205374% |  eq vio: 4.3697271 |  ineq vio: 0.1310766 |
Epoch 5 | Train loss: 0.0129395 |  Test mse: 0.0338513 |  opt gap: -0.0210325% |  eq vio: 3.6292424 |  ineq vio: 0.3260539 |
Epoch 6 | Train loss: 0.0134695 |  Test mse: 0.0272655 |  opt gap: 0.0168451% |  eq vio: 4.5053144 |  ineq vio: 0.1942282 |
Epoch 7 | Train loss: 0.0130876 |  Test mse: 0.0351490 |  opt gap: -0.0221618% |  eq vio: 5.2860394 |  ineq vio: 0.1906422 |
Epoch 8 | Train loss: 0.0131127 |  Test mse: 0.0293311 |  opt gap: 0.0102810% |  eq vio: 4.7175493 |  ineq vio: 0.1940410 |
Epoch 9 | Train loss: 0.0118880 |  Test mse: 0.0267553 |  opt gap: 0.0001221% |  eq vio: 4.5469532 |  ineq vio: 0.3473282 |
Epoch 10 | Train loss: 0.0110427 |  Test mse: 0.0257969 |  opt gap: -0.0044440% |  eq vio: 4.2719746 |  ineq vio: 0.3629869 |
Epoch 11 | Train loss: 0.0110592 |  Test mse: 0.0290502 |  opt gap: 0.0448464% |  eq vio: 4.8235655 |  ineq vio: 0.1441557 |
Epoch 12 | Train loss: 0.0120050 |  Test mse: 0.0482653 |  opt gap: -0.0276516% |  eq vio: 4.0837569 |  ineq vio: 0.5783308 |
Epoch 13 | Train loss: 0.0111553 |  Test mse: 0.0250018 |  opt gap: -0.0186977% |  eq vio: 4.7196569 |  ineq vio: 0.4870586 |
Epoch 14 | Train loss: 0.0088753 |  Test mse: 0.0271844 |  opt gap: -0.0222244% |  eq vio: 7.3014493 |  ineq vio: 0.7758080 |
Epoch 15 | Train loss: 0.0106312 |  Test mse: 0.0280659 |  opt gap: 0.0019673% |  eq vio: 5.2455249 |  ineq vio: 0.0820722 |
Epoch 16 | Train loss: 0.0089812 |  Test mse: 0.0241020 |  opt gap: 0.0016627% |  eq vio: 4.1348863 |  ineq vio: 0.2601269 |
Epoch 17 | Train loss: 0.0093084 |  Test mse: 0.0165953 |  opt gap: 0.0244600% |  eq vio: 4.4807868 |  ineq vio: 0.1661629 |
Epoch 18 | Train loss: 0.0093514 |  Test mse: 0.0171167 |  opt gap: 0.0080986% |  eq vio: 4.0235910 |  ineq vio: 0.1221360 |
Epoch 19 | Train loss: 0.0095875 |  Test mse: 0.0151077 |  opt gap: -0.0094415% |  eq vio: 4.3867974 |  ineq vio: 0.5966623 |
Epoch 20 | Train loss: 0.0084202 |  Test mse: 0.0227898 |  opt gap: 0.0211391% |  eq vio: 4.4490252 |  ineq vio: 0.1236107 |
Epoch 21 | Train loss: 0.0095428 |  Test mse: 0.0190714 |  opt gap: 0.0193402% |  eq vio: 4.8587332 |  ineq vio: 0.0729182 |
Epoch 22 | Train loss: 0.0085567 |  Test mse: 0.0182696 |  opt gap: 0.0062932% |  eq vio: 4.6554523 |  ineq vio: 0.0683581 |
Epoch 23 | Train loss: 0.0087708 |  Test mse: 0.0153197 |  opt gap: 0.0339358% |  eq vio: 4.3356676 |  ineq vio: 0.1730874 |
Epoch 24 | Train loss: 0.0094577 |  Test mse: 0.0258200 |  opt gap: -0.0027307% |  eq vio: 4.9034195 |  ineq vio: 0.2983519 |
Epoch 25 | Train loss: 0.0065243 |  Test mse: 0.0252326 |  opt gap: 0.0298325% |  eq vio: 5.0482430 |  ineq vio: 0.0739758 |
Epoch 26 | Train loss: 0.0107066 |  Test mse: 0.0246569 |  opt gap: 0.0036978% |  eq vio: 4.5489597 |  ineq vio: 0.0971106 |
Epoch 27 | Train loss: 0.0071492 |  Test mse: 0.0182320 |  opt gap: -0.0069273% |  eq vio: 4.2154617 |  ineq vio: 0.2951040 |
Epoch 28 | Train loss: 0.0078986 |  Test mse: 0.0240850 |  opt gap: 0.0003711% |  eq vio: 4.5324330 |  ineq vio: 0.1547614 |
Epoch 29 | Train loss: 0.0076952 |  Test mse: 0.0269244 |  opt gap: 0.0110159% |  eq vio: 5.0974779 |  ineq vio: 0.1288060 |
Epoch 30 | Train loss: 0.0076902 |  Test mse: 0.0160343 |  opt gap: 0.0105690% |  eq vio: 4.1688943 |  ineq vio: 0.2896003 |
Epoch 31 | Train loss: 0.0061598 |  Test mse: 0.0148734 |  opt gap: 0.0167561% |  eq vio: 4.3364697 |  ineq vio: 0.2304488 |
Epoch 32 | Train loss: 0.0068569 |  Test mse: 0.0168513 |  opt gap: -0.0000041% |  eq vio: 4.8941522 |  ineq vio: 0.0757915 |
Epoch 33 | Train loss: 0.0080494 |  Test mse: 0.0137393 |  opt gap: 0.0056612% |  eq vio: 4.9524760 |  ineq vio: 0.0533198 |
Epoch 34 | Train loss: 0.0067669 |  Test mse: 0.0157540 |  opt gap: 0.0162423% |  eq vio: 4.6649685 |  ineq vio: 0.2251306 |
Epoch 35 | Train loss: 0.0069160 |  Test mse: 0.0157432 |  opt gap: 0.0193034% |  eq vio: 5.0176029 |  ineq vio: 0.1954132 |
Epoch 36 | Train loss: 0.0073638 |  Test mse: 0.0211386 |  opt gap: 0.0005130% |  eq vio: 4.2800016 |  ineq vio: 0.1031462 |
Epoch 37 | Train loss: 0.0074998 |  Test mse: 0.0159116 |  opt gap: 0.0252465% |  eq vio: 4.5529351 |  ineq vio: 0.1725689 |
Epoch 38 | Train loss: 0.0070112 |  Test mse: 0.0245643 |  opt gap: -0.0079687% |  eq vio: 4.5282102 |  ineq vio: 0.4212972 |
Epoch 39 | Train loss: 0.0054699 |  Test mse: 0.0239061 |  opt gap: 0.0242095% |  eq vio: 5.4120073 |  ineq vio: 0.3369166 |
Epoch 40 | Train loss: 0.0067564 |  Test mse: 0.0149167 |  opt gap: -0.0069861% |  eq vio: 5.8921714 |  ineq vio: 0.2520503 |
Epoch 41 | Train loss: 0.0077301 |  Test mse: 0.0344276 |  opt gap: 0.0068165% |  eq vio: 5.4049168 |  ineq vio: 0.4596540 |
Epoch 42 | Train loss: 0.0057423 |  Test mse: 0.0118047 |  opt gap: 0.0082855% |  eq vio: 5.1360054 |  ineq vio: 0.2223969 |
Epoch 43 | Train loss: 0.0060431 |  Test mse: 0.0189283 |  opt gap: 0.0053730% |  eq vio: 4.4609380 |  ineq vio: 0.1139801 |
Epoch 44 | Train loss: 0.0067735 |  Test mse: 0.0181304 |  opt gap: 0.0010483% |  eq vio: 4.8081613 |  ineq vio: 0.3137003 |
Epoch 45 | Train loss: 0.0057521 |  Test mse: 0.0272836 |  opt gap: -0.0051979% |  eq vio: 4.1814260 |  ineq vio: 0.1396413 |
Epoch 46 | Train loss: 0.0083929 |  Test mse: 0.0116319 |  opt gap: 0.0046511% |  eq vio: 3.7385359 |  ineq vio: 0.2533643 |
Epoch 47 | Train loss: 0.0066563 |  Test mse: 0.0257604 |  opt gap: -0.0141230% |  eq vio: 5.1696920 |  ineq vio: 0.4320346 |
Epoch 48 | Train loss: 0.0056119 |  Test mse: 0.0144909 |  opt gap: 0.0172142% |  eq vio: 4.4040051 |  ineq vio: 0.0841568 |
Epoch 49 | Train loss: 0.0052755 |  Test mse: 0.0169243 |  opt gap: -0.0015360% |  eq vio: 3.9360943 |  ineq vio: 0.1576870 |
Epoch 50 | Train loss: 0.0063572 |  Test mse: 0.0159415 |  opt gap: 0.0087093% |  eq vio: 4.1603203 |  ineq vio: 0.1402071 |

# Model RNN

In [56]:
class RecurrentNetwork(nn.Module):
    def __init__(self, x_size, y_size, hidden_dim, num_layers):
        super().__init__()
        self.hidden_dim = hidden_dim
        self.num_layers = num_layers

        # LSTM layer
        self.rnn = nn.LSTM(input_size=x_size, hidden_size=hidden_dim, num_layers=num_layers, batch_first=True)
        self.fc = nn.Linear(hidden_dim, y_size)

    def forward(self, x):
        # x shape: (batch_size, seq_size, x_size)
        if x.dim() == 2:
            x = x.unsqueeze(1)
        # Initialize hidden state and cell state
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_dim).to(x.device)
        c0 = torch.zeros(self.num_layers, x.size(0), self.hidden_dim).to(x.device)

        out, _ = self.rnn(x, (h0, c0)) # outshape: (batch_size, seq_len, hidden_dim)
        out = out[:, -1, :] #(batch_size, hidden_dim)
        out = self.fc(out)
        return out

In [57]:
model_rnn = RecurrentNetwork(x_size=len(inputs),
                             y_size=len(outputs),
                             hidden_dim=32,
                             num_layers=2).to(device)

In [58]:
resutl_4 = model_train_test(train_data_loader, test_data_loader, model_rnn, nn.MSELoss(), opf_metric, epochs=50)

==============================================Start training on cuda===========================================
Epoch 1 | Train loss: 1.6954482 |  Test mse: 0.3561234 |  opt gap: -0.0279395% |  eq vio: 11.7757988 |  ineq vio: 0.0490910 |
Epoch 2 | Train loss: 0.2886111 |  Test mse: 0.3282022 |  opt gap: 0.0309470% |  eq vio: 9.3524494 |  ineq vio: 0.0543624 |
Epoch 3 | Train loss: 0.2810066 |  Test mse: 0.3219217 |  opt gap: 0.0273309% |  eq vio: 10.4592381 |  ineq vio: 0.0575419 |
Epoch 4 | Train loss: 0.2718753 |  Test mse: 0.3119617 |  opt gap: 0.0184183% |  eq vio: 13.4044819 |  ineq vio: 0.2383816 |
Epoch 5 | Train loss: 0.2553548 |  Test mse: 0.2800147 |  opt gap: 0.0088912% |  eq vio: 25.8451080 |  ineq vio: 3.1909409 |
Epoch 6 | Train loss: 0.2065717 |  Test mse: 0.2178358 |  opt gap: 0.0138423% |  eq vio: 25.4468575 |  ineq vio: 2.2864606 |
Epoch 7 | Train loss: 0.1630523 |  Test mse: 0.1711095 |  opt gap: 0.0023964% |  eq vio: 28.7024403 |  ineq vio: 3.8419907 |
Epoch 8 | Train loss: 0.1297686 |  Test mse: 0.1395428 |  opt gap: -0.0026489% |  eq vio: 30.0545063 |  ineq vio: 4.0797253 |
Epoch 9 | Train loss: 0.1071875 |  Test mse: 0.1200034 |  opt gap: 0.0004273% |  eq vio: 29.6244659 |  ineq vio: 3.8871429 |
Epoch 10 | Train loss: 0.0919373 |  Test mse: 0.1065043 |  opt gap: 0.0057310% |  eq vio: 27.4088097 |  ineq vio: 3.1532445 |
Epoch 11 | Train loss: 0.0813337 |  Test mse: 0.0960161 |  opt gap: 0.0053513% |  eq vio: 22.2886696 |  ineq vio: 2.1401322 |
Epoch 12 | Train loss: 0.0736957 |  Test mse: 0.0916986 |  opt gap: -0.0016459% |  eq vio: 19.4840889 |  ineq vio: 1.7617255 |
Epoch 13 | Train loss: 0.0682610 |  Test mse: 0.0870218 |  opt gap: 0.0034898% |  eq vio: 18.7098808 |  ineq vio: 2.0379066 |
Epoch 14 | Train loss: 0.0637203 |  Test mse: 0.0819611 |  opt gap: 0.0004203% |  eq vio: 18.2863770 |  ineq vio: 2.2177262 |
Epoch 15 | Train loss: 0.0596095 |  Test mse: 0.0791119 |  opt gap: 0.0077694% |  eq vio: 18.8547630 |  ineq vio: 2.0642526 |
Epoch 16 | Train loss: 0.0558911 |  Test mse: 0.0741901 |  opt gap: 0.0066553% |  eq vio: 20.2222443 |  ineq vio: 2.5327151 |
Epoch 17 | Train loss: 0.0526037 |  Test mse: 0.0709478 |  opt gap: 0.0045348% |  eq vio: 18.8041687 |  ineq vio: 1.9537930 |
Epoch 18 | Train loss: 0.0497771 |  Test mse: 0.0666562 |  opt gap: 0.0080280% |  eq vio: 16.5270176 |  ineq vio: 1.6062855 |
Epoch 19 | Train loss: 0.0473916 |  Test mse: 0.0648026 |  opt gap: 0.0086760% |  eq vio: 16.6497154 |  ineq vio: 1.5310693 |
Epoch 20 | Train loss: 0.0452734 |  Test mse: 0.0627811 |  opt gap: -0.0079219% |  eq vio: 14.7633781 |  ineq vio: 1.0546645 |
Epoch 21 | Train loss: 0.0432430 |  Test mse: 0.0606592 |  opt gap: 0.0114112% |  eq vio: 13.9327354 |  ineq vio: 0.9298831 |
Epoch 22 | Train loss: 0.0415883 |  Test mse: 0.0599720 |  opt gap: -0.0050523% |  eq vio: 13.1506634 |  ineq vio: 0.8953919 |
Epoch 23 | Train loss: 0.0397295 |  Test mse: 0.0563219 |  opt gap: -0.0021003% |  eq vio: 12.6345606 |  ineq vio: 0.6390489 |
Epoch 24 | Train loss: 0.0382517 |  Test mse: 0.0551901 |  opt gap: 0.0064192% |  eq vio: 10.9903831 |  ineq vio: 0.5705342 |
Epoch 25 | Train loss: 0.0367827 |  Test mse: 0.0533429 |  opt gap: 0.0029442% |  eq vio: 10.3545771 |  ineq vio: 0.5641554 |
Epoch 26 | Train loss: 0.0354855 |  Test mse: 0.0525752 |  opt gap: -0.0014308% |  eq vio: 9.6196136 |  ineq vio: 0.2671070 |
Epoch 27 | Train loss: 0.0342498 |  Test mse: 0.0511530 |  opt gap: 0.0026195% |  eq vio: 8.6866007 |  ineq vio: 0.2959952 |
Epoch 28 | Train loss: 0.0331211 |  Test mse: 0.0495705 |  opt gap: -0.0147119% |  eq vio: 8.0059166 |  ineq vio: 0.2545632 |
Epoch 29 | Train loss: 0.0322587 |  Test mse: 0.0490116 |  opt gap: -0.0117316% |  eq vio: 7.8158264 |  ineq vio: 0.2770914 |
Epoch 30 | Train loss: 0.0313989 |  Test mse: 0.0472687 |  opt gap: 0.0003750% |  eq vio: 7.3686090 |  ineq vio: 0.2176951 |
Epoch 31 | Train loss: 0.0307986 |  Test mse: 0.0460083 |  opt gap: 0.0195004% |  eq vio: 7.4597063 |  ineq vio: 0.3086794 |
Epoch 32 | Train loss: 0.0302093 |  Test mse: 0.0458861 |  opt gap: 0.0114583% |  eq vio: 7.2173052 |  ineq vio: 0.1825116 |
Epoch 33 | Train loss: 0.0295004 |  Test mse: 0.0454843 |  opt gap: 0.0022573% |  eq vio: 6.1717649 |  ineq vio: 0.2289213 |
Epoch 34 | Train loss: 0.0290753 |  Test mse: 0.0458723 |  opt gap: -0.0037764% |  eq vio: 6.3531570 |  ineq vio: 0.2392498 |
Epoch 35 | Train loss: 0.0285944 |  Test mse: 0.0444274 |  opt gap: -0.0026178% |  eq vio: 6.2651353 |  ineq vio: 0.2272167 |
Epoch 36 | Train loss: 0.0281471 |  Test mse: 0.0445107 |  opt gap: -0.0044998% |  eq vio: 6.5537624 |  ineq vio: 0.2840378 |
Epoch 37 | Train loss: 0.0276420 |  Test mse: 0.0433996 |  opt gap: 0.0130303% |  eq vio: 6.3786073 |  ineq vio: 0.2020163 |
Epoch 38 | Train loss: 0.0270973 |  Test mse: 0.0427151 |  opt gap: 0.0150555% |  eq vio: 5.6365528 |  ineq vio: 0.2414152 |
Epoch 39 | Train loss: 0.0265424 |  Test mse: 0.0419568 |  opt gap: -0.0027189% |  eq vio: 6.2063541 |  ineq vio: 0.1677399 |
Epoch 40 | Train loss: 0.0262682 |  Test mse: 0.0429170 |  opt gap: -0.0031954% |  eq vio: 5.8773084 |  ineq vio: 0.1650111 |
Epoch 41 | Train loss: 0.0258749 |  Test mse: 0.0418537 |  opt gap: 0.0229318% |  eq vio: 6.6828489 |  ineq vio: 0.2299138 |
Epoch 42 | Train loss: 0.0254035 |  Test mse: 0.0412791 |  opt gap: -0.0058861% |  eq vio: 6.4205899 |  ineq vio: 0.2299991 |
Epoch 43 | Train loss: 0.0250327 |  Test mse: 0.0406042 |  opt gap: 0.0150961% |  eq vio: 6.5655994 |  ineq vio: 0.1712450 |
Epoch 44 | Train loss: 0.0245169 |  Test mse: 0.0420746 |  opt gap: -0.0005981% |  eq vio: 6.3965111 |  ineq vio: 0.1885922 |
Epoch 45 | Train loss: 0.0241501 |  Test mse: 0.0393842 |  opt gap: 0.0023058% |  eq vio: 6.2776904 |  ineq vio: 0.1988034 |
Epoch 46 | Train loss: 0.0238401 |  Test mse: 0.0405169 |  opt gap: 0.0055465% |  eq vio: 5.6262064 |  ineq vio: 0.1931801 |
Epoch 47 | Train loss: 0.0234597 |  Test mse: 0.0395709 |  opt gap: 0.0034942% |  eq vio: 5.9934368 |  ineq vio: 0.1599751 |
Epoch 48 | Train loss: 0.0230506 |  Test mse: 0.0394123 |  opt gap: 0.0048293% |  eq vio: 6.0190363 |  ineq vio: 0.1783665 |
Epoch 49 | Train loss: 0.0226903 |  Test mse: 0.0406105 |  opt gap: -0.0147140% |  eq vio: 5.8107505 |  ineq vio: 0.2675461 |
Epoch 50 | Train loss: 0.0223293 |  Test mse: 0.0398374 |  opt gap: 0.0065232% |  eq vio: 6.4287271 |  ineq vio: 0.1829657 |

In [59]:
resutl_5 = model_train_test(train_data_loader, test_data_loader, model_rnn, MSEPenaltyLoss(opf_metric), opf_metric, epochs=50, penalty=True)

==============================================Start training on cuda===========================================
Epoch 1 | Train loss: 0.0756021 |  Test mse: 0.0401667 |  opt gap: 0.0089543% |  eq vio: 4.4033384 |  ineq vio: 0.1371771 |
Epoch 2 | Train loss: 0.0587954 |  Test mse: 0.0403263 |  opt gap: 0.0015840% |  eq vio: 2.8320074 |  ineq vio: 0.1289976 |
Epoch 3 | Train loss: 0.0539948 |  Test mse: 0.0424130 |  opt gap: -0.0073716% |  eq vio: 2.1543694 |  ineq vio: 0.1214719 |
Epoch 4 | Train loss: 0.0499817 |  Test mse: 0.0413913 |  opt gap: 0.0015000% |  eq vio: 2.2238343 |  ineq vio: 0.1501550 |
Epoch 5 | Train loss: 0.0469162 |  Test mse: 0.0409530 |  opt gap: -0.0045310% |  eq vio: 1.9141877 |  ineq vio: 0.1512432 |
Epoch 6 | Train loss: 0.0463906 |  Test mse: 0.0404935 |  opt gap: -0.0017007% |  eq vio: 1.6132426 |  ineq vio: 0.1338589 |
Epoch 7 | Train loss: 0.0460059 |  Test mse: 0.0402311 |  opt gap: 0.0016525% |  eq vio: 2.7447681 |  ineq vio: 0.1395830 |
Epoch 8 | Train loss: 0.0439452 |  Test mse: 0.0411263 |  opt gap: 0.0000594% |  eq vio: 2.3402338 |  ineq vio: 0.1367668 |
Epoch 9 | Train loss: 0.0419740 |  Test mse: 0.0415533 |  opt gap: -0.0007621% |  eq vio: 1.7962928 |  ineq vio: 0.1442605 |
Epoch 10 | Train loss: 0.0418404 |  Test mse: 0.0419557 |  opt gap: 0.0021292% |  eq vio: 2.3183098 |  ineq vio: 0.1074356 |
Epoch 11 | Train loss: 0.0426556 |  Test mse: 0.0402377 |  opt gap: -0.0006136% |  eq vio: 1.5661068 |  ineq vio: 0.1204667 |
Epoch 12 | Train loss: 0.0410901 |  Test mse: 0.0412154 |  opt gap: -0.0002819% |  eq vio: 2.1229439 |  ineq vio: 0.1395591 |
Epoch 13 | Train loss: 0.0407756 |  Test mse: 0.0404339 |  opt gap: -0.0005901% |  eq vio: 1.3688108 |  ineq vio: 0.1371198 |
Epoch 14 | Train loss: 0.0400849 |  Test mse: 0.0404868 |  opt gap: 0.0075138% |  eq vio: 2.4756694 |  ineq vio: 0.1311368 |
Epoch 15 | Train loss: 0.0390052 |  Test mse: 0.0414882 |  opt gap: 0.0091831% |  eq vio: 1.1964604 |  ineq vio: 0.1125608 |
Epoch 16 | Train loss: 0.0397640 |  Test mse: 0.0394838 |  opt gap: 0.0103280% |  eq vio: 1.2643303 |  ineq vio: 0.1144509 |
Epoch 17 | Train loss: 0.0389713 |  Test mse: 0.0395288 |  opt gap: 0.0053977% |  eq vio: 1.7076693 |  ineq vio: 0.1124865 |
Epoch 18 | Train loss: 0.0385814 |  Test mse: 0.0396055 |  opt gap: 0.0068839% |  eq vio: 1.1653147 |  ineq vio: 0.1113577 |
Epoch 19 | Train loss: 0.0393740 |  Test mse: 0.0393009 |  opt gap: 0.0084324% |  eq vio: 1.2167561 |  ineq vio: 0.1224401 |
Epoch 20 | Train loss: 0.0390311 |  Test mse: 0.0396108 |  opt gap: -0.0077438% |  eq vio: 1.6682369 |  ineq vio: 0.1054222 |
Epoch 21 | Train loss: 0.0387644 |  Test mse: 0.0395375 |  opt gap: 0.0090185% |  eq vio: 1.9274222 |  ineq vio: 0.1439351 |
Epoch 22 | Train loss: 0.0371472 |  Test mse: 0.0421218 |  opt gap: 0.0023344% |  eq vio: 1.4915880 |  ineq vio: 0.1290327 |
Epoch 23 | Train loss: 0.0378415 |  Test mse: 0.0385975 |  opt gap: 0.0000088% |  eq vio: 2.0168316 |  ineq vio: 0.1838882 |
Epoch 24 | Train loss: 0.0378423 |  Test mse: 0.0398196 |  opt gap: 0.0028388% |  eq vio: 1.9217498 |  ineq vio: 0.1203282 |
Epoch 25 | Train loss: 0.0363232 |  Test mse: 0.0397216 |  opt gap: 0.0056674% |  eq vio: 1.7114477 |  ineq vio: 0.1309869 |
Epoch 26 | Train loss: 0.0368852 |  Test mse: 0.0404312 |  opt gap: -0.0058836% |  eq vio: 1.3933830 |  ineq vio: 0.1314244 |
Epoch 27 | Train loss: 0.0379640 |  Test mse: 0.0390304 |  opt gap: -0.0030787% |  eq vio: 2.0899825 |  ineq vio: 0.1535595 |
Epoch 28 | Train loss: 0.0360721 |  Test mse: 0.0387584 |  opt gap: -0.0025791% |  eq vio: 1.1998433 |  ineq vio: 0.1000551 |
Epoch 29 | Train loss: 0.0374979 |  Test mse: 0.0389510 |  opt gap: 0.0016439% |  eq vio: 1.9776483 |  ineq vio: 0.1218609 |
Epoch 30 | Train loss: 0.0370672 |  Test mse: 0.0378992 |  opt gap: 0.0012141% |  eq vio: 1.7515210 |  ineq vio: 0.1576073 |
Epoch 31 | Train loss: 0.0373228 |  Test mse: 0.0395351 |  opt gap: -0.0048288% |  eq vio: 1.1676760 |  ineq vio: 0.1095653 |
Epoch 32 | Train loss: 0.0368805 |  Test mse: 0.0389570 |  opt gap: -0.0014823% |  eq vio: 1.0785061 |  ineq vio: 0.1153278 |
Epoch 33 | Train loss: 0.0367191 |  Test mse: 0.0386466 |  opt gap: -0.0049715% |  eq vio: 1.8587883 |  ineq vio: 0.1359424 |
Epoch 34 | Train loss: 0.0360838 |  Test mse: 0.0392732 |  opt gap: 0.0011440% |  eq vio: 1.8541192 |  ineq vio: 0.1349390 |
Epoch 35 | Train loss: 0.0366843 |  Test mse: 0.0390231 |  opt gap: 0.0023055% |  eq vio: 1.0758007 |  ineq vio: 0.1127180 |
Epoch 36 | Train loss: 0.0344466 |  Test mse: 0.0379160 |  opt gap: -0.0008504% |  eq vio: 0.9105129 |  ineq vio: 0.1112773 |
Epoch 37 | Train loss: 0.0358773 |  Test mse: 0.0388447 |  opt gap: 0.0005371% |  eq vio: 1.5444316 |  ineq vio: 0.1706524 |
Epoch 38 | Train loss: 0.0359241 |  Test mse: 0.0389826 |  opt gap: 0.0073187% |  eq vio: 1.7786671 |  ineq vio: 0.1436590 |
Epoch 39 | Train loss: 0.0354370 |  Test mse: 0.0378419 |  opt gap: -0.0037045% |  eq vio: 2.0788183 |  ineq vio: 0.1139246 |
Epoch 40 | Train loss: 0.0343668 |  Test mse: 0.0397406 |  opt gap: -0.0038220% |  eq vio: 1.1475556 |  ineq vio: 0.1454483 |
Epoch 41 | Train loss: 0.0355724 |  Test mse: 0.0391173 |  opt gap: 0.0097508% |  eq vio: 1.0623696 |  ineq vio: 0.1168605 |
Epoch 42 | Train loss: 0.0360989 |  Test mse: 0.0375868 |  opt gap: -0.0013668% |  eq vio: 1.2327085 |  ineq vio: 0.1016081 |
Epoch 43 | Train loss: 0.0336036 |  Test mse: 0.0371668 |  opt gap: 0.0082193% |  eq vio: 1.5289860 |  ineq vio: 0.1168146 |
Epoch 44 | Train loss: 0.0355040 |  Test mse: 0.0395141 |  opt gap: -0.0036525% |  eq vio: 1.1460886 |  ineq vio: 0.1260528 |
Epoch 45 | Train loss: 0.0349626 |  Test mse: 0.0366589 |  opt gap: 0.0016342% |  eq vio: 1.6900010 |  ineq vio: 0.1173158 |
Epoch 46 | Train loss: 0.0356482 |  Test mse: 0.0393896 |  opt gap: 0.0044823% |  eq vio: 1.8181179 |  ineq vio: 0.1520198 |
Epoch 47 | Train loss: 0.0354398 |  Test mse: 0.0371303 |  opt gap: 0.0101273% |  eq vio: 1.0800440 |  ineq vio: 0.1159353 |
Epoch 48 | Train loss: 0.0351010 |  Test mse: 0.0388506 |  opt gap: -0.0005377% |  eq vio: 1.5265882 |  ineq vio: 0.1262860 |
Epoch 49 | Train loss: 0.0333457 |  Test mse: 0.0374816 |  opt gap: -0.0037047% |  eq vio: 1.2303898 |  ineq vio: 0.1151374 |
Epoch 50 | Train loss: 0.0362695 |  Test mse: 0.0394297 |  opt gap: -0.0027506% |  eq vio: 1.7968764 |  ineq vio: 0.0960892 |

# MLP model

In [60]:
class NeuralNetwork(nn.Module):
    def __init__(self, x_size=3, y_size=5, width=32, depth=3):
        super().__init__()
        NN = [nn.Linear(x_size, width)]
        for _ in range(depth):
            NN.append(nn.Linear(width, width))
            NN.append(nn.ReLU())
        NN.append(nn.Linear(width, y_size))
        self.NN = nn.Sequential(*NN)
    def forward(self, x):
        y = self.NN(x)
        return y

In [61]:
model_base = NeuralNetwork(x_size=len(inputs),
                          y_size=len(outputs),
                          width=32,
                          depth=2).to(device)

results = model_train_test(train_data_loader, test_data_loader, model_base, nn.MSELoss(), opf_metric, epochs=50)

==============================================Start training on cuda===========================================
Epoch 1 | Train loss: 0.8852510 |  Test mse: 0.2678800 |  opt gap: 0.0211753% |  eq vio: 225.4129333 |  ineq vio: 88.8420563 |
Epoch 2 | Train loss: 0.1874891 |  Test mse: 0.1689313 |  opt gap: 0.0086749% |  eq vio: 123.3648376 |  ineq vio: 43.5044479 |
Epoch 3 | Train loss: 0.1561301 |  Test mse: 0.1517129 |  opt gap: 0.0237959% |  eq vio: 81.9214249 |  ineq vio: 21.7540398 |
Epoch 4 | Train loss: 0.1425775 |  Test mse: 0.1455908 |  opt gap: 0.0149567% |  eq vio: 71.0983963 |  ineq vio: 18.6453400 |
Epoch 5 | Train loss: 0.1298699 |  Test mse: 0.1402443 |  opt gap: 0.0186115% |  eq vio: 66.2074280 |  ineq vio: 15.7131662 |
Epoch 6 | Train loss: 0.1150909 |  Test mse: 0.1175856 |  opt gap: 0.0233613% |  eq vio: 59.1141396 |  ineq vio: 13.5611248 |
Epoch 7 | Train loss: 0.0965847 |  Test mse: 0.1025167 |  opt gap: 0.0189477% |  eq vio: 62.3640060 |  ineq vio: 14.7731209 |
Epoch 8 | Train loss: 0.0766313 |  Test mse: 0.0826882 |  opt gap: -0.0064916% |  eq vio: 48.7582932 |  ineq vio: 11.5523758 |
Epoch 9 | Train loss: 0.0629667 |  Test mse: 0.0774589 |  opt gap: -0.0022071% |  eq vio: 35.3459473 |  ineq vio: 7.1987114 |
Epoch 10 | Train loss: 0.0571914 |  Test mse: 0.0730010 |  opt gap: 0.0073143% |  eq vio: 31.1744022 |  ineq vio: 4.4564810 |
Epoch 11 | Train loss: 0.0527530 |  Test mse: 0.0654202 |  opt gap: 0.0246343% |  eq vio: 30.8081684 |  ineq vio: 5.3600230 |
Epoch 12 | Train loss: 0.0486352 |  Test mse: 0.0650469 |  opt gap: -0.0032520% |  eq vio: 29.1435432 |  ineq vio: 4.7882233 |
Epoch 13 | Train loss: 0.0449141 |  Test mse: 0.0601177 |  opt gap: -0.0117712% |  eq vio: 33.1295319 |  ineq vio: 6.7380676 |
Epoch 14 | Train loss: 0.0425372 |  Test mse: 0.0584821 |  opt gap: -0.0100144% |  eq vio: 33.6104431 |  ineq vio: 6.4149237 |
Epoch 15 | Train loss: 0.0403825 |  Test mse: 0.0562693 |  opt gap: -0.0018866% |  eq vio: 31.0526943 |  ineq vio: 4.8591566 |
Epoch 16 | Train loss: 0.0383888 |  Test mse: 0.0510399 |  opt gap: -0.0098775% |  eq vio: 29.1598129 |  ineq vio: 4.4738498 |
Epoch 17 | Train loss: 0.0370315 |  Test mse: 0.0521312 |  opt gap: -0.0017409% |  eq vio: 28.7023010 |  ineq vio: 5.4953222 |
Epoch 18 | Train loss: 0.0356717 |  Test mse: 0.0487204 |  opt gap: 0.0043808% |  eq vio: 27.2644634 |  ineq vio: 4.4539523 |
Epoch 19 | Train loss: 0.0346783 |  Test mse: 0.0483970 |  opt gap: 0.0020631% |  eq vio: 24.5023327 |  ineq vio: 4.2694502 |
Epoch 20 | Train loss: 0.0337514 |  Test mse: 0.0457198 |  opt gap: 0.0025261% |  eq vio: 23.8111763 |  ineq vio: 3.6285074 |
Epoch 21 | Train loss: 0.0328914 |  Test mse: 0.0451945 |  opt gap: 0.0061177% |  eq vio: 22.7124443 |  ineq vio: 3.1532636 |
Epoch 22 | Train loss: 0.0323125 |  Test mse: 0.0471049 |  opt gap: -0.0002538% |  eq vio: 22.8120975 |  ineq vio: 2.7081709 |
Epoch 23 | Train loss: 0.0314682 |  Test mse: 0.0457511 |  opt gap: 0.0130486% |  eq vio: 19.7075558 |  ineq vio: 2.2479160 |
Epoch 24 | Train loss: 0.0311817 |  Test mse: 0.0454324 |  opt gap: 0.0109184% |  eq vio: 20.0267487 |  ineq vio: 2.2812660 |
Epoch 25 | Train loss: 0.0303184 |  Test mse: 0.0441441 |  opt gap: 0.0094542% |  eq vio: 23.7986259 |  ineq vio: 4.1589003 |
Epoch 26 | Train loss: 0.0299040 |  Test mse: 0.0448319 |  opt gap: -0.0006480% |  eq vio: 17.1952610 |  ineq vio: 1.6986243 |
Epoch 27 | Train loss: 0.0292836 |  Test mse: 0.0445563 |  opt gap: -0.0092983% |  eq vio: 16.8245335 |  ineq vio: 0.6296122 |
Epoch 28 | Train loss: 0.0290556 |  Test mse: 0.0439601 |  opt gap: -0.0067873% |  eq vio: 15.6676855 |  ineq vio: 0.8359786 |
Epoch 29 | Train loss: 0.0288839 |  Test mse: 0.0422285 |  opt gap: 0.0022443% |  eq vio: 20.5701351 |  ineq vio: 1.3026326 |
Epoch 30 | Train loss: 0.0283022 |  Test mse: 0.0401077 |  opt gap: -0.0060184% |  eq vio: 19.3475266 |  ineq vio: 3.2178907 |
Epoch 31 | Train loss: 0.0280871 |  Test mse: 0.0392908 |  opt gap: 0.0069952% |  eq vio: 17.4002762 |  ineq vio: 1.1279287 |
Epoch 32 | Train loss: 0.0276718 |  Test mse: 0.0400509 |  opt gap: 0.0095725% |  eq vio: 17.9972496 |  ineq vio: 2.0332561 |
Epoch 33 | Train loss: 0.0275230 |  Test mse: 0.0388819 |  opt gap: 0.0038594% |  eq vio: 15.1994190 |  ineq vio: 1.5048144 |
Epoch 34 | Train loss: 0.0271450 |  Test mse: 0.0425278 |  opt gap: -0.0030300% |  eq vio: 17.6904564 |  ineq vio: 1.3240892 |
Epoch 35 | Train loss: 0.0269939 |  Test mse: 0.0407957 |  opt gap: 0.0137580% |  eq vio: 13.5657749 |  ineq vio: 1.5109861 |
Epoch 36 | Train loss: 0.0268910 |  Test mse: 0.0404449 |  opt gap: 0.0029744% |  eq vio: 17.5677185 |  ineq vio: 1.8886821 |
Epoch 37 | Train loss: 0.0263253 |  Test mse: 0.0415798 |  opt gap: 0.0034732% |  eq vio: 16.5886230 |  ineq vio: 1.9321735 |
Epoch 38 | Train loss: 0.0262217 |  Test mse: 0.0387425 |  opt gap: 0.0098389% |  eq vio: 13.2620335 |  ineq vio: 1.2520459 |
Epoch 39 | Train loss: 0.0257535 |  Test mse: 0.0393338 |  opt gap: 0.0028710% |  eq vio: 14.7369938 |  ineq vio: 1.8293664 |
Epoch 40 | Train loss: 0.0257378 |  Test mse: 0.0401564 |  opt gap: 0.0004252% |  eq vio: 15.1974916 |  ineq vio: 1.9093008 |
Epoch 41 | Train loss: 0.0256594 |  Test mse: 0.0403500 |  opt gap: 0.0069781% |  eq vio: 15.6087284 |  ineq vio: 1.9153070 |
Epoch 42 | Train loss: 0.0254008 |  Test mse: 0.0393946 |  opt gap: -0.0007227% |  eq vio: 12.7290268 |  ineq vio: 0.9555116 |
Epoch 43 | Train loss: 0.0251096 |  Test mse: 0.0406191 |  opt gap: 0.0051283% |  eq vio: 13.4250774 |  ineq vio: 0.7589217 |
Epoch 44 | Train loss: 0.0250856 |  Test mse: 0.0402689 |  opt gap: -0.0010983% |  eq vio: 14.4298086 |  ineq vio: 1.6551626 |
Epoch 45 | Train loss: 0.0251775 |  Test mse: 0.0379734 |  opt gap: 0.0030290% |  eq vio: 13.7206841 |  ineq vio: 0.7816796 |
Epoch 46 | Train loss: 0.0248354 |  Test mse: 0.0406915 |  opt gap: 0.0021541% |  eq vio: 14.5381584 |  ineq vio: 1.4081398 |
Epoch 47 | Train loss: 0.0246146 |  Test mse: 0.0386605 |  opt gap: 0.0050827% |  eq vio: 13.7182722 |  ineq vio: 0.7512949 |
Epoch 48 | Train loss: 0.0244263 |  Test mse: 0.0403671 |  opt gap: 0.0101812% |  eq vio: 15.9411430 |  ineq vio: 1.6838368 |
Epoch 49 | Train loss: 0.0243611 |  Test mse: 0.0379191 |  opt gap: -0.0133054% |  eq vio: 14.5322437 |  ineq vio: 1.2081866 |
Epoch 50 | Train loss: 0.0242019 |  Test mse: 0.0389011 |  opt gap: 0.0034141% |  eq vio: 13.6660633 |  ineq vio: 1.3046930 |

In [62]:
results_1 = model_train_test(train_data_loader, test_data_loader, model_base, MSEPenaltyLoss(opf_metric), opf_metric, epochs=50, penalty=True)

==============================================Start training on cuda===========================================
Epoch 1 | Train loss: 0.1478204 |  Test mse: 0.0447742 |  opt gap: -0.0003002% |  eq vio: 6.3838167 |  ineq vio: 0.3077147 |
Epoch 2 | Train loss: 0.1129617 |  Test mse: 0.0471497 |  opt gap: -0.0010167% |  eq vio: 6.7282553 |  ineq vio: 0.2128766 |
Epoch 3 | Train loss: 0.1074474 |  Test mse: 0.0477372 |  opt gap: -0.0028505% |  eq vio: 5.5179272 |  ineq vio: 0.3712055 |
Epoch 4 | Train loss: 0.1014206 |  Test mse: 0.0471158 |  opt gap: -0.0019473% |  eq vio: 5.6106439 |  ineq vio: 0.2431101 |
Epoch 5 | Train loss: 0.1050206 |  Test mse: 0.0462440 |  opt gap: -0.0013022% |  eq vio: 4.1881967 |  ineq vio: 0.2683710 |
Epoch 6 | Train loss: 0.0973152 |  Test mse: 0.0444487 |  opt gap: 0.0024465% |  eq vio: 4.0629616 |  ineq vio: 0.1386177 |
Epoch 7 | Train loss: 0.0924564 |  Test mse: 0.0444705 |  opt gap: -0.0008569% |  eq vio: 3.8357878 |  ineq vio: 0.3323562 |
Epoch 8 | Train loss: 0.0942469 |  Test mse: 0.0434988 |  opt gap: 0.0006127% |  eq vio: 6.3984113 |  ineq vio: 0.5543905 |
Epoch 9 | Train loss: 0.0912941 |  Test mse: 0.0434798 |  opt gap: -0.0011324% |  eq vio: 8.5012836 |  ineq vio: 0.3897913 |
Epoch 10 | Train loss: 0.0957436 |  Test mse: 0.0435554 |  opt gap: -0.0025946% |  eq vio: 3.2357435 |  ineq vio: 0.1632406 |
Epoch 11 | Train loss: 0.0875010 |  Test mse: 0.0424612 |  opt gap: -0.0015348% |  eq vio: 5.7548008 |  ineq vio: 0.1996975 |
Epoch 12 | Train loss: 0.1017718 |  Test mse: 0.0447790 |  opt gap: 0.0007667% |  eq vio: 3.3667023 |  ineq vio: 0.2429503 |
Epoch 13 | Train loss: 0.0859655 |  Test mse: 0.0413819 |  opt gap: -0.0012503% |  eq vio: 6.2695136 |  ineq vio: 0.2664439 |
Epoch 14 | Train loss: 0.0838338 |  Test mse: 0.0411997 |  opt gap: 0.0015942% |  eq vio: 6.0797482 |  ineq vio: 0.4028663 |
Epoch 15 | Train loss: 0.0840140 |  Test mse: 0.0406464 |  opt gap: -0.0011656% |  eq vio: 3.0819650 |  ineq vio: 0.1397863 |
Epoch 16 | Train loss: 0.0877944 |  Test mse: 0.0425240 |  opt gap: -0.0008129% |  eq vio: 3.8976707 |  ineq vio: 0.3431890 |
Epoch 17 | Train loss: 0.0844192 |  Test mse: 0.0400475 |  opt gap: 0.0018164% |  eq vio: 10.1163454 |  ineq vio: 1.1279315 |
Epoch 18 | Train loss: 0.0884839 |  Test mse: 0.0405306 |  opt gap: 0.0016601% |  eq vio: 3.3746977 |  ineq vio: 0.2237688 |
Epoch 19 | Train loss: 0.0825434 |  Test mse: 0.0405065 |  opt gap: -0.0013142% |  eq vio: 3.5868387 |  ineq vio: 0.1255208 |
Epoch 20 | Train loss: 0.0850581 |  Test mse: 0.0391067 |  opt gap: -0.0040185% |  eq vio: 3.8442688 |  ineq vio: 0.2240160 |
Epoch 21 | Train loss: 0.0837850 |  Test mse: 0.0397321 |  opt gap: -0.0047207% |  eq vio: 4.5543780 |  ineq vio: 0.2903880 |
Epoch 22 | Train loss: 0.0820622 |  Test mse: 0.0402124 |  opt gap: -0.0041484% |  eq vio: 6.4627786 |  ineq vio: 0.4193775 |
Epoch 23 | Train loss: 0.0888727 |  Test mse: 0.0411584 |  opt gap: 0.0000790% |  eq vio: 5.6464310 |  ineq vio: 0.3205894 |
Epoch 24 | Train loss: 0.0839256 |  Test mse: 0.0410901 |  opt gap: 0.0020020% |  eq vio: 3.7500484 |  ineq vio: 0.2425768 |
Epoch 25 | Train loss: 0.0757984 |  Test mse: 0.0398100 |  opt gap: -0.0016713% |  eq vio: 3.6355622 |  ineq vio: 0.1894470 |
Epoch 26 | Train loss: 0.0766181 |  Test mse: 0.0400511 |  opt gap: -0.0022344% |  eq vio: 2.4923515 |  ineq vio: 0.2069519 |
Epoch 27 | Train loss: 0.0746543 |  Test mse: 0.0387983 |  opt gap: -0.0026836% |  eq vio: 5.7080865 |  ineq vio: 0.2473675 |
Epoch 28 | Train loss: 0.0765235 |  Test mse: 0.0382889 |  opt gap: 0.0006286% |  eq vio: 3.1099343 |  ineq vio: 0.1467906 |
Epoch 29 | Train loss: 0.0742546 |  Test mse: 0.0382993 |  opt gap: -0.0000896% |  eq vio: 2.9791775 |  ineq vio: 0.2379676 |
Epoch 30 | Train loss: 0.0774390 |  Test mse: 0.0383998 |  opt gap: 0.0021003% |  eq vio: 10.8742752 |  ineq vio: 0.3132496 |
Epoch 31 | Train loss: 0.0756014 |  Test mse: 0.0378781 |  opt gap: 0.0019590% |  eq vio: 2.7451532 |  ineq vio: 0.1931014 |
Epoch 32 | Train loss: 0.0808125 |  Test mse: 0.0381794 |  opt gap: 0.0032134% |  eq vio: 6.2757645 |  ineq vio: 0.3394654 |
Epoch 33 | Train loss: 0.0732037 |  Test mse: 0.0382204 |  opt gap: 0.0005017% |  eq vio: 5.7304249 |  ineq vio: 0.1633418 |
Epoch 34 | Train loss: 0.0768773 |  Test mse: 0.0380074 |  opt gap: -0.0030579% |  eq vio: 3.6041634 |  ineq vio: 0.1340054 |
Epoch 35 | Train loss: 0.0739245 |  Test mse: 0.0387651 |  opt gap: 0.0014719% |  eq vio: 2.8959658 |  ineq vio: 0.1944639 |
Epoch 36 | Train loss: 0.0770650 |  Test mse: 0.0372274 |  opt gap: -0.0010227% |  eq vio: 3.6530843 |  ineq vio: 0.2560775 |
Epoch 37 | Train loss: 0.0701799 |  Test mse: 0.0380434 |  opt gap: 0.0010694% |  eq vio: 3.0603104 |  ineq vio: 0.1187597 |
Epoch 38 | Train loss: 0.0710393 |  Test mse: 0.0360498 |  opt gap: -0.0023332% |  eq vio: 4.7834163 |  ineq vio: 0.1674567 |
Epoch 39 | Train loss: 0.0752727 |  Test mse: 0.0379046 |  opt gap: 0.0050106% |  eq vio: 5.2554522 |  ineq vio: 0.1570168 |
Epoch 40 | Train loss: 0.0701657 |  Test mse: 0.0380924 |  opt gap: 0.0041402% |  eq vio: 3.1885498 |  ineq vio: 0.2629360 |
Epoch 41 | Train loss: 0.0750034 |  Test mse: 0.0379795 |  opt gap: 0.0023815% |  eq vio: 5.7627916 |  ineq vio: 0.0912917 |
Epoch 42 | Train loss: 0.0671371 |  Test mse: 0.0369557 |  opt gap: 0.0068833% |  eq vio: 6.9926682 |  ineq vio: 0.1701792 |
Epoch 43 | Train loss: 0.0692767 |  Test mse: 0.0373745 |  opt gap: 0.0028635% |  eq vio: 1.9049945 |  ineq vio: 0.1621231 |
Epoch 44 | Train loss: 0.0673670 |  Test mse: 0.0378819 |  opt gap: -0.0024679% |  eq vio: 4.9744568 |  ineq vio: 0.1199128 |
Epoch 45 | Train loss: 0.0691893 |  Test mse: 0.0363811 |  opt gap: 0.0005324% |  eq vio: 4.4327469 |  ineq vio: 0.2221247 |
Epoch 46 | Train loss: 0.0694992 |  Test mse: 0.0368281 |  opt gap: 0.0038805% |  eq vio: 2.4719720 |  ineq vio: 0.1462000 |
Epoch 47 | Train loss: 0.0694491 |  Test mse: 0.0375218 |  opt gap: 0.0037601% |  eq vio: 3.8932886 |  ineq vio: 0.1209119 |
Epoch 48 | Train loss: 0.0681159 |  Test mse: 0.0374762 |  opt gap: 0.0009760% |  eq vio: 3.9352574 |  ineq vio: 0.1801856 |
Epoch 49 | Train loss: 0.0667212 |  Test mse: 0.0357021 |  opt gap: -0.0015320% |  eq vio: 2.9660285 |  ineq vio: 0.1916746 |
Epoch 50 | Train loss: 0.0687063 |  Test mse: 0.0362602 |  opt gap: 0.0041661% |  eq vio: 5.8863692 |  ineq vio: 0.1100137 |